package cn.mutu.land.model;

// Generated 2016-8-18 17:18:22 by Hibernate Tools 4.0.0

/**
 * BusInfo generated by hbm2java
 */
public class BusInfo implements java.io.Serializable {

	private int busId;
	private String busName;
	private String busAddress;
	private int busWorker;

	public BusInfo() {
	}

	public BusInfo(int busId, int busWorker) {
		this.busId = busId;
		this.busWorker = busWorker;
	}

	public BusInfo(int busId, String busName, String busAddress, int busWorker) {
		this.busId = busId;
		this.busName = busName;
		this.busAddress = busAddress;
		this.busWorker = busWorker;
	}

	public int getBusId() {
		return this.busId;
	}

	public void setBusId(int busId) {
		this.busId = busId;
	}

	public String getBusName() {
		return this.busName;
	}

	public void setBusName(String busName) {
		this.busName = busName;
	}

	public String getBusAddress() {
		return this.busAddress;
	}

	public void setBusAddress(String busAddress) {
		this.busAddress = busAddress;
	}

	public int getBusWorker() {
		return this.busWorker;
	}

	public void setBusWorker(int busWorker) {
		this.busWorker = busWorker;
	}

}
