package cn.mutu.land.model;

// Generated 2016-9-3 14:07:21 by Hibernate Tools 4.0.0

/**
 * BusinessInfo generated by hbm2java
 */
public class BusinessInfo implements java.io.Serializable {

	private int businessId;
	private String businessName;
	private String businessAddress;
	private Integer businessZdcode;
	private String businessEvalueRange;
	private String businessIndustryType;
	private Integer businessIndustryCode;
	private Integer businessWorker;
	private String businessKfq;
	private Integer businessKfqCode;
	private String businessKfqType;
	private int businessDevArea;
	private int businessAdvance;
	private double businessPreInvestment;
	private double businessActInvestment;
	private double businessIncome;
	private double businessProduct;
	private double businessTax;
	private double businessArea;
	private double businessArea1;
	private Double businessArea2;
	private Double businessArea3;
	private Double businessArea4;
	private Double businessArea5;
	private Double businessArea6;
	private Double businessArea7;
	private Double businessBuildingArea;
	private Double businessPlotRatio;
	private Double businessOutdoorArea;
	private Double businessBuildingCoeficient;

	public BusinessInfo() {
	}

	public BusinessInfo(int businessId, int businessDevArea,
			int businessAdvance, double businessPreInvestment,
			double businessActInvestment, double businessIncome,
			double businessProduct, double businessTax, double businessArea,
			double businessArea1) {
		this.businessId = businessId;
		this.businessDevArea = businessDevArea;
		this.businessAdvance = businessAdvance;
		this.businessPreInvestment = businessPreInvestment;
		this.businessActInvestment = businessActInvestment;
		this.businessIncome = businessIncome;
		this.businessProduct = businessProduct;
		this.businessTax = businessTax;
		this.businessArea = businessArea;
		this.businessArea1 = businessArea1;
	}

	public BusinessInfo(int businessId, String businessName,
			String businessAddress, Integer businessZdcode,
			String businessEvalueRange, String businessIndustryType,
			Integer businessIndustryCode, Integer businessWorker,
			String businessKfq, Integer businessKfqCode,
			String businessKfqType, int businessDevArea, int businessAdvance,
			double businessPreInvestment, double businessActInvestment,
			double businessIncome, double businessProduct, double businessTax,
			double businessArea, double businessArea1, Double businessArea2,
			Double businessArea3, Double businessArea4, Double businessArea5,
			Double businessArea6, Double businessArea7,
			Double businessBuildingArea, Double businessPlotRatio,
			Double businessOutdoorArea, Double businessBuildingCoeficient) {
		this.businessId = businessId;
		this.businessName = businessName;
		this.businessAddress = businessAddress;
		this.businessZdcode = businessZdcode;
		this.businessEvalueRange = businessEvalueRange;
		this.businessIndustryType = businessIndustryType;
		this.businessIndustryCode = businessIndustryCode;
		this.businessWorker = businessWorker;
		this.businessKfq = businessKfq;
		this.businessKfqCode = businessKfqCode;
		this.businessKfqType = businessKfqType;
		this.businessDevArea = businessDevArea;
		this.businessAdvance = businessAdvance;
		this.businessPreInvestment = businessPreInvestment;
		this.businessActInvestment = businessActInvestment;
		this.businessIncome = businessIncome;
		this.businessProduct = businessProduct;
		this.businessTax = businessTax;
		this.businessArea = businessArea;
		this.businessArea1 = businessArea1;
		this.businessArea2 = businessArea2;
		this.businessArea3 = businessArea3;
		this.businessArea4 = businessArea4;
		this.businessArea5 = businessArea5;
		this.businessArea6 = businessArea6;
		this.businessArea7 = businessArea7;
		this.businessBuildingArea = businessBuildingArea;
		this.businessPlotRatio = businessPlotRatio;
		this.businessOutdoorArea = businessOutdoorArea;
		this.businessBuildingCoeficient = businessBuildingCoeficient;
	}

	public int getBusinessId() {
		return this.businessId;
	}

	public void setBusinessId(int businessId) {
		this.businessId = businessId;
	}

	public String getBusinessName() {
		return this.businessName;
	}

	public void setBusinessName(String businessName) {
		this.businessName = businessName;
	}

	public String getBusinessAddress() {
		return this.businessAddress;
	}

	public void setBusinessAddress(String businessAddress) {
		this.businessAddress = businessAddress;
	}

	public Integer getBusinessZdcode() {
		return this.businessZdcode;
	}

	public void setBusinessZdcode(Integer businessZdcode) {
		this.businessZdcode = businessZdcode;
	}

	public String getBusinessEvalueRange() {
		return this.businessEvalueRange;
	}

	public void setBusinessEvalueRange(String businessEvalueRange) {
		this.businessEvalueRange = businessEvalueRange;
	}

	public String getBusinessIndustryType() {
		return this.businessIndustryType;
	}

	public void setBusinessIndustryType(String businessIndustryType) {
		this.businessIndustryType = businessIndustryType;
	}

	public Integer getBusinessIndustryCode() {
		return this.businessIndustryCode;
	}

	public void setBusinessIndustryCode(Integer businessIndustryCode) {
		this.businessIndustryCode = businessIndustryCode;
	}

	public Integer getBusinessWorker() {
		return this.businessWorker;
	}

	public void setBusinessWorker(Integer businessWorker) {
		this.businessWorker = businessWorker;
	}

	public String getBusinessKfq() {
		return this.businessKfq;
	}

	public void setBusinessKfq(String businessKfq) {
		this.businessKfq = businessKfq;
	}

	public Integer getBusinessKfqCode() {
		return this.businessKfqCode;
	}

	public void setBusinessKfqCode(Integer businessKfqCode) {
		this.businessKfqCode = businessKfqCode;
	}

	public String getBusinessKfqType() {
		return this.businessKfqType;
	}

	public void setBusinessKfqType(String businessKfqType) {
		this.businessKfqType = businessKfqType;
	}

	public int getBusinessDevArea() {
		return this.businessDevArea;
	}

	public void setBusinessDevArea(int businessDevArea) {
		this.businessDevArea = businessDevArea;
	}

	public int getBusinessAdvance() {
		return this.businessAdvance;
	}

	public void setBusinessAdvance(int businessAdvance) {
		this.businessAdvance = businessAdvance;
	}

	public double getBusinessPreInvestment() {
		return this.businessPreInvestment;
	}

	public void setBusinessPreInvestment(double businessPreInvestment) {
		this.businessPreInvestment = businessPreInvestment;
	}

	public double getBusinessActInvestment() {
		return this.businessActInvestment;
	}

	public void setBusinessActInvestment(double businessActInvestment) {
		this.businessActInvestment = businessActInvestment;
	}

	public double getBusinessIncome() {
		return this.businessIncome;
	}

	public void setBusinessIncome(double businessIncome) {
		this.businessIncome = businessIncome;
	}

	public double getBusinessProduct() {
		return this.businessProduct;
	}

	public void setBusinessProduct(double businessProduct) {
		this.businessProduct = businessProduct;
	}

	public double getBusinessTax() {
		return this.businessTax;
	}

	public void setBusinessTax(double businessTax) {
		this.businessTax = businessTax;
	}

	public double getBusinessArea() {
		return this.businessArea;
	}

	public void setBusinessArea(double businessArea) {
		this.businessArea = businessArea;
	}

	public double getBusinessArea1() {
		return this.businessArea1;
	}

	public void setBusinessArea1(double businessArea1) {
		this.businessArea1 = businessArea1;
	}

	public Double getBusinessArea2() {
		return this.businessArea2;
	}

	public void setBusinessArea2(Double businessArea2) {
		this.businessArea2 = businessArea2;
	}

	public Double getBusinessArea3() {
		return this.businessArea3;
	}

	public void setBusinessArea3(Double businessArea3) {
		this.businessArea3 = businessArea3;
	}

	public Double getBusinessArea4() {
		return this.businessArea4;
	}

	public void setBusinessArea4(Double businessArea4) {
		this.businessArea4 = businessArea4;
	}

	public Double getBusinessArea5() {
		return this.businessArea5;
	}

	public void setBusinessArea5(Double businessArea5) {
		this.businessArea5 = businessArea5;
	}

	public Double getBusinessArea6() {
		return this.businessArea6;
	}

	public void setBusinessArea6(Double businessArea6) {
		this.businessArea6 = businessArea6;
	}

	public Double getBusinessArea7() {
		return this.businessArea7;
	}

	public void setBusinessArea7(Double businessArea7) {
		this.businessArea7 = businessArea7;
	}

	public Double getBusinessBuildingArea() {
		return this.businessBuildingArea;
	}

	public void setBusinessBuildingArea(Double businessBuildingArea) {
		this.businessBuildingArea = businessBuildingArea;
	}

	public Double getBusinessPlotRatio() {
		return this.businessPlotRatio;
	}

	public void setBusinessPlotRatio(Double businessPlotRatio) {
		this.businessPlotRatio = businessPlotRatio;
	}

	public Double getBusinessOutdoorArea() {
		return this.businessOutdoorArea;
	}

	public void setBusinessOutdoorArea(Double businessOutdoorArea) {
		this.businessOutdoorArea = businessOutdoorArea;
	}

	public Double getBusinessBuildingCoeficient() {
		return this.businessBuildingCoeficient;
	}

	public void setBusinessBuildingCoeficient(Double businessBuildingCoeficient) {
		this.businessBuildingCoeficient = businessBuildingCoeficient;
	}

}
