package cn.mutu.land.model;

// Generated 2016-6-17 22:26:09 by Hibernate Tools 4.0.0

/**
 * BusinessMap generated by hbm2java
 */
public class BusinessMap implements java.io.Serializable {

	private Integer id;
	private String proCode;
	private String uploadUser;
	private double westCoor;
	private double eastCoor;
	private double northCoor;
	private double southCoor;
	private int isPass;

	public BusinessMap() {
	}

	public BusinessMap(String proCode, double westCoor, double eastCoor,
			double northCoor, double southCoor, int isPass) {
		this.proCode = proCode;
		this.westCoor = westCoor;
		this.eastCoor = eastCoor;
		this.northCoor = northCoor;
		this.southCoor = southCoor;
		this.isPass = isPass;
	}

	public BusinessMap(String proCode, String uploadUser, double westCoor,
			double eastCoor, double northCoor, double southCoor, int isPass) {
		this.proCode = proCode;
		this.uploadUser = uploadUser;
		this.westCoor = westCoor;
		this.eastCoor = eastCoor;
		this.northCoor = northCoor;
		this.southCoor = southCoor;
		this.isPass = isPass;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getProCode() {
		return this.proCode;
	}

	public void setProCode(String proCode) {
		this.proCode = proCode;
	}

	public String getUploadUser() {
		return this.uploadUser;
	}

	public void setUploadUser(String uploadUser) {
		this.uploadUser = uploadUser;
	}

	public double getWestCoor() {
		return this.westCoor;
	}

	public void setWestCoor(double westCoor) {
		this.westCoor = westCoor;
	}

	public double getEastCoor() {
		return this.eastCoor;
	}

	public void setEastCoor(double eastCoor) {
		this.eastCoor = eastCoor;
	}

	public double getNorthCoor() {
		return this.northCoor;
	}

	public void setNorthCoor(double northCoor) {
		this.northCoor = northCoor;
	}

	public double getSouthCoor() {
		return this.southCoor;
	}

	public void setSouthCoor(double southCoor) {
		this.southCoor = southCoor;
	}

	public int getIsPass() {
		return this.isPass;
	}

	public void setIsPass(int isPass) {
		this.isPass = isPass;
	}

}
