package cn.mutu.land.model;

// Generated 2016-9-3 13:13:05 by Hibernate Tools 4.0.0

/**
 * BusinessPhoto generated by hbm2java
 */
public class BusinessPhoto implements java.io.Serializable {

	private Integer id;
	private String proCode;
	private String uploadUser;
	private String upDate;
	private String photoPath;
	private String photoTitle;
	private int isPass;
	private String other;

	public BusinessPhoto() {
	}

	public BusinessPhoto(String upDate, int isPass) {
		this.upDate = upDate;
		this.isPass = isPass;
	}

	public BusinessPhoto(String proCode, String uploadUser, String upDate,
			String photoPath, String photoTitle, int isPass, String other) {
		this.proCode = proCode;
		this.uploadUser = uploadUser;
		this.upDate = upDate;
		this.photoPath = photoPath;
		this.photoTitle = photoTitle;
		this.isPass = isPass;
		this.other = other;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getProCode() {
		return this.proCode;
	}

	public void setProCode(String proCode) {
		this.proCode = proCode;
	}

	public String getUploadUser() {
		return this.uploadUser;
	}

	public void setUploadUser(String uploadUser) {
		this.uploadUser = uploadUser;
	}

	public String getUpDate() {
		return this.upDate;
	}

	public void setUpDate(String upDate) {
		this.upDate = upDate;
	}

	public String getPhotoPath() {
		return this.photoPath;
	}

	public void setPhotoPath(String photoPath) {
		this.photoPath = photoPath;
	}

	public String getPhotoTitle() {
		return this.photoTitle;
	}

	public void setPhotoTitle(String photoTitle) {
		this.photoTitle = photoTitle;
	}

	public int getIsPass() {
		return this.isPass;
	}

	public void setIsPass(int isPass) {
		this.isPass = isPass;
	}

	public String getOther() {
		return this.other;
	}

	public void setOther(String other) {
		this.other = other;
	}

}
