package cn.mutu.land.model;

<<<<<<< HEAD
// Generated 2016-6-22 17:21:39 by Hibernate Tools 4.0.0
=======
// Generated 2016-6-16 22:53:53 by Hibernate Tools 4.0.0
>>>>>>> c827f56ad6128fb79072d22195127b46b34209dc

import java.util.Date;

/**
 * BusinessPhoto generated by hbm2java
 */
public class BusinessPhoto implements java.io.Serializable {

	private int id;
	private String proCode;
	private String uploadUser;
	private Date upDate;
	private String photoPath;
	private String photoTitle;
	private int isPass;
	private String other;

	public BusinessPhoto() {
	}

	public BusinessPhoto(int id, int isPass) {
		this.id = id;
		this.isPass = isPass;
	}

	public BusinessPhoto(int id, String proCode, String uploadUser,
			Date upDate, String photoPath, String photoTitle, int isPass,
			String other) {
		this.id = id;
		this.proCode = proCode;
		this.uploadUser = uploadUser;
		this.upDate = upDate;
		this.photoPath = photoPath;
		this.photoTitle = photoTitle;
		this.isPass = isPass;
		this.other = other;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getProCode() {
		return this.proCode;
	}

	public void setProCode(String proCode) {
		this.proCode = proCode;
	}

<<<<<<< HEAD
	public String getUploadUser() {
		return this.uploadUser;
	}

	public void setUploadUser(String uploadUser) {
		this.uploadUser = uploadUser;
	}

=======
>>>>>>> c827f56ad6128fb79072d22195127b46b34209dc
	public Date getUpDate() {
		return this.upDate;
	}

	public void setUpDate(Date upDate) {
		this.upDate = upDate;
	}

	public String getPhotoPath() {
		return this.photoPath;
	}

	public void setPhotoPath(String photoPath) {
		this.photoPath = photoPath;
	}

	public String getPhotoTitle() {
		return this.photoTitle;
	}

	public void setPhotoTitle(String photoTitle) {
		this.photoTitle = photoTitle;
	}

	public int getIsPass() {
		return this.isPass;
	}

	public void setIsPass(int isPass) {
		this.isPass = isPass;
	}

	public String getOther() {
		return this.other;
	}

	public void setOther(String other) {
		this.other = other;
	}

}
