package cn.mutu.land.model;

// Generated 2016-9-13 1:30:06 by Hibernate Tools 4.0.0

/**
 * DevTask generated by hbm2java
 */
public class DevTask implements java.io.Serializable {

	private Integer id;
	private String taskComment;
	private String taskFinish;
	private String taskWindow;

	public DevTask() {
	}

	public DevTask(String taskComment, String taskFinish, String taskWindow) {
		this.taskComment = taskComment;
		this.taskFinish = taskFinish;
		this.taskWindow = taskWindow;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTaskComment() {
		return this.taskComment;
	}

	public void setTaskComment(String taskComment) {
		this.taskComment = taskComment;
	}

	public String getTaskFinish() {
		return this.taskFinish;
	}

	public void setTaskFinish(String taskFinish) {
		this.taskFinish = taskFinish;
	}

	public String getTaskWindow() {
		return this.taskWindow;
	}

	public void setTaskWindow(String taskWindow) {
		this.taskWindow = taskWindow;
	}

}
