package cn.mutu.land.model;

// Generated 2016-8-31 17:44:18 by Hibernate Tools 4.0.0

/**
 * EntQyjyd generated by hbm2java
 */
public class EntQyjyd implements java.io.Serializable {

	private Integer id;
	private Integer mbbsm;
	private String ysdm;
	private String kfqdm;
	private String kfqmc;
	private String tbbh;
	private String dxdm;
	private String qymc;
	private String qydz;
	private String sspjfw;
	private String hylb;
	private String hydm;
	private Integer qyrs;
	private Double qyydmj;
	private Double cfpt;
	private Double xzbg;
	private Double ltcd;
	private Double nbyld;
	private Double dltcc;
	private Double ld;
	private Double qt;
	private Double zjzmj;
	private Double rjl;
	private Double jdzmj;
	private Double jzxs;
	private String bz;
	private String jydfz;

	public EntQyjyd() {
	}

	public EntQyjyd(String tbbh) {
		this.tbbh = tbbh;
	}

	public EntQyjyd(Integer mbbsm, String ysdm, String kfqdm, String kfqmc,
			String tbbh, String dxdm, String qymc, String qydz, String sspjfw,
			String hylb, String hydm, Integer qyrs, Double qyydmj, Double cfpt,
			Double xzbg, Double ltcd, Double nbyld, Double dltcc, Double ld,
			Double qt, Double zjzmj, Double rjl, Double jdzmj, Double jzxs,
			String bz, String jydfz) {
		this.mbbsm = mbbsm;
		this.ysdm = ysdm;
		this.kfqdm = kfqdm;
		this.kfqmc = kfqmc;
		this.tbbh = tbbh;
		this.dxdm = dxdm;
		this.qymc = qymc;
		this.qydz = qydz;
		this.sspjfw = sspjfw;
		this.hylb = hylb;
		this.hydm = hydm;
		this.qyrs = qyrs;
		this.qyydmj = qyydmj;
		this.cfpt = cfpt;
		this.xzbg = xzbg;
		this.ltcd = ltcd;
		this.nbyld = nbyld;
		this.dltcc = dltcc;
		this.ld = ld;
		this.qt = qt;
		this.zjzmj = zjzmj;
		this.rjl = rjl;
		this.jdzmj = jdzmj;
		this.jzxs = jzxs;
		this.bz = bz;
		this.jydfz = jydfz;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getMbbsm() {
		return this.mbbsm;
	}

	public void setMbbsm(Integer mbbsm) {
		this.mbbsm = mbbsm;
	}

	public String getYsdm() {
		return this.ysdm;
	}

	public void setYsdm(String ysdm) {
		this.ysdm = ysdm;
	}

	public String getKfqdm() {
		return this.kfqdm;
	}

	public void setKfqdm(String kfqdm) {
		this.kfqdm = kfqdm;
	}

	public String getKfqmc() {
		return this.kfqmc;
	}

	public void setKfqmc(String kfqmc) {
		this.kfqmc = kfqmc;
	}

	public String getTbbh() {
		return this.tbbh;
	}

	public void setTbbh(String tbbh) {
		this.tbbh = tbbh;
	}

	public String getDxdm() {
		return this.dxdm;
	}

	public void setDxdm(String dxdm) {
		this.dxdm = dxdm;
	}

	public String getQymc() {
		return this.qymc;
	}

	public void setQymc(String qymc) {
		this.qymc = qymc;
	}

	public String getQydz() {
		return this.qydz;
	}

	public void setQydz(String qydz) {
		this.qydz = qydz;
	}

	public String getSspjfw() {
		return this.sspjfw;
	}

	public void setSspjfw(String sspjfw) {
		this.sspjfw = sspjfw;
	}

	public String getHylb() {
		return this.hylb;
	}

	public void setHylb(String hylb) {
		this.hylb = hylb;
	}

	public String getHydm() {
		return this.hydm;
	}

	public void setHydm(String hydm) {
		this.hydm = hydm;
	}

	public Integer getQyrs() {
		return this.qyrs;
	}

	public void setQyrs(Integer qyrs) {
		this.qyrs = qyrs;
	}

	public Double getQyydmj() {
		return this.qyydmj;
	}

	public void setQyydmj(Double qyydmj) {
		this.qyydmj = qyydmj;
	}

	public Double getCfpt() {
		return this.cfpt;
	}

	public void setCfpt(Double cfpt) {
		this.cfpt = cfpt;
	}

	public Double getXzbg() {
		return this.xzbg;
	}

	public void setXzbg(Double xzbg) {
		this.xzbg = xzbg;
	}

	public Double getLtcd() {
		return this.ltcd;
	}

	public void setLtcd(Double ltcd) {
		this.ltcd = ltcd;
	}

	public Double getNbyld() {
		return this.nbyld;
	}

	public void setNbyld(Double nbyld) {
		this.nbyld = nbyld;
	}

	public Double getDltcc() {
		return this.dltcc;
	}

	public void setDltcc(Double dltcc) {
		this.dltcc = dltcc;
	}

	public Double getLd() {
		return this.ld;
	}

	public void setLd(Double ld) {
		this.ld = ld;
	}

	public Double getQt() {
		return this.qt;
	}

	public void setQt(Double qt) {
		this.qt = qt;
	}

	public Double getZjzmj() {
		return this.zjzmj;
	}

	public void setZjzmj(Double zjzmj) {
		this.zjzmj = zjzmj;
	}

	public Double getRjl() {
		return this.rjl;
	}

	public void setRjl(Double rjl) {
		this.rjl = rjl;
	}

	public Double getJdzmj() {
		return this.jdzmj;
	}

	public void setJdzmj(Double jdzmj) {
		this.jdzmj = jdzmj;
	}

	public Double getJzxs() {
		return this.jzxs;
	}

	public void setJzxs(Double jzxs) {
		this.jzxs = jzxs;
	}

	public String getBz() {
		return this.bz;
	}

	public void setBz(String bz) {
		this.bz = bz;
	}

	public String getJydfz() {
		return this.jydfz;
	}

	public void setJydfz(String jydfz) {
		this.jydfz = jydfz;
	}

}
