package cn.mutu.land.model;

// Generated 2016-9-2 19:11:26 by Hibernate Tools 4.0.0

/**
 * KfqInfomation generated by hbm2java
 */
public class KfqInfomation implements java.io.Serializable {

	private Integer kfqId;
	private String kfqdm;
	private String kfqmc;
	private String kfqjb;
	private String kfqsplx;
	private String kfqpjfw;
	private String slsj;
	private String spdw;
	private String gljg;
	private String gljgdz;
	private String zdcy;
	private Float sptdzmj;
	private Float MKfqpjmj;
	private Float DKfqpjmj;
	private String kfqpjlx;
	private Float MTdkfl;
	private Float DTdkfl;
	private Integer MCzrk;
	private Integer DCzrk;
	private Float MGdzctzze;
	private Float DGdzctzze;
	private Float MEscyssze;
	private Float DEscyssze;
	private Float MGyzsr;
	private Float DGyzsr;
	private Float MGyssze;
	private Float DGyssze;
	private Float MGxzsr;
	private Float DGxzsr;
	private Float MGxssze;
	private Float DGxssze;
	private String MXm;
	private String MKqtzsj;
	private Float MKqtzmj;
	private Float MKqtzhmj;
	private String bz;

	public KfqInfomation() {
	}

	public KfqInfomation(String kfqdm, String kfqmc, String kfqjb,
			String kfqsplx, String kfqpjfw, String slsj, String spdw,
			String gljg, String gljgdz, String zdcy, Float sptdzmj,
			Float MKfqpjmj, Float DKfqpjmj, String kfqpjlx, Float MTdkfl,
			Float DTdkfl, Integer MCzrk, Integer DCzrk, Float MGdzctzze,
			Float DGdzctzze, Float MEscyssze, Float DEscyssze, Float MGyzsr,
			Float DGyzsr, Float MGyssze, Float DGyssze, Float MGxzsr,
			Float DGxzsr, Float MGxssze, Float DGxssze, String MXm,
			String MKqtzsj, Float MKqtzmj, Float MKqtzhmj, String bz) {
		this.kfqdm = kfqdm;
		this.kfqmc = kfqmc;
		this.kfqjb = kfqjb;
		this.kfqsplx = kfqsplx;
		this.kfqpjfw = kfqpjfw;
		this.slsj = slsj;
		this.spdw = spdw;
		this.gljg = gljg;
		this.gljgdz = gljgdz;
		this.zdcy = zdcy;
		this.sptdzmj = sptdzmj;
		this.MKfqpjmj = MKfqpjmj;
		this.DKfqpjmj = DKfqpjmj;
		this.kfqpjlx = kfqpjlx;
		this.MTdkfl = MTdkfl;
		this.DTdkfl = DTdkfl;
		this.MCzrk = MCzrk;
		this.DCzrk = DCzrk;
		this.MGdzctzze = MGdzctzze;
		this.DGdzctzze = DGdzctzze;
		this.MEscyssze = MEscyssze;
		this.DEscyssze = DEscyssze;
		this.MGyzsr = MGyzsr;
		this.DGyzsr = DGyzsr;
		this.MGyssze = MGyssze;
		this.DGyssze = DGyssze;
		this.MGxzsr = MGxzsr;
		this.DGxzsr = DGxzsr;
		this.MGxssze = MGxssze;
		this.DGxssze = DGxssze;
		this.MXm = MXm;
		this.MKqtzsj = MKqtzsj;
		this.MKqtzmj = MKqtzmj;
		this.MKqtzhmj = MKqtzhmj;
		this.bz = bz;
	}

	public Integer getKfqId() {
		return this.kfqId;
	}

	public void setKfqId(Integer kfqId) {
		this.kfqId = kfqId;
	}

	public String getKfqdm() {
		return this.kfqdm;
	}

	public void setKfqdm(String kfqdm) {
		this.kfqdm = kfqdm;
	}

	public String getKfqmc() {
		return this.kfqmc;
	}

	public void setKfqmc(String kfqmc) {
		this.kfqmc = kfqmc;
	}

	public String getKfqjb() {
		return this.kfqjb;
	}

	public void setKfqjb(String kfqjb) {
		this.kfqjb = kfqjb;
	}

	public String getKfqsplx() {
		return this.kfqsplx;
	}

	public void setKfqsplx(String kfqsplx) {
		this.kfqsplx = kfqsplx;
	}

	public String getKfqpjfw() {
		return this.kfqpjfw;
	}

	public void setKfqpjfw(String kfqpjfw) {
		this.kfqpjfw = kfqpjfw;
	}

	public String getSlsj() {
		return this.slsj;
	}

	public void setSlsj(String slsj) {
		this.slsj = slsj;
	}

	public String getSpdw() {
		return this.spdw;
	}

	public void setSpdw(String spdw) {
		this.spdw = spdw;
	}

	public String getGljg() {
		return this.gljg;
	}

	public void setGljg(String gljg) {
		this.gljg = gljg;
	}

	public String getGljgdz() {
		return this.gljgdz;
	}

	public void setGljgdz(String gljgdz) {
		this.gljgdz = gljgdz;
	}

	public String getZdcy() {
		return this.zdcy;
	}

	public void setZdcy(String zdcy) {
		this.zdcy = zdcy;
	}

	public Float getSptdzmj() {
		return this.sptdzmj;
	}

	public void setSptdzmj(Float sptdzmj) {
		this.sptdzmj = sptdzmj;
	}

	public Float getMKfqpjmj() {
		return this.MKfqpjmj;
	}

	public void setMKfqpjmj(Float MKfqpjmj) {
		this.MKfqpjmj = MKfqpjmj;
	}

	public Float getDKfqpjmj() {
		return this.DKfqpjmj;
	}

	public void setDKfqpjmj(Float DKfqpjmj) {
		this.DKfqpjmj = DKfqpjmj;
	}

	public String getKfqpjlx() {
		return this.kfqpjlx;
	}

	public void setKfqpjlx(String kfqpjlx) {
		this.kfqpjlx = kfqpjlx;
	}

	public Float getMTdkfl() {
		return this.MTdkfl;
	}

	public void setMTdkfl(Float MTdkfl) {
		this.MTdkfl = MTdkfl;
	}

	public Float getDTdkfl() {
		return this.DTdkfl;
	}

	public void setDTdkfl(Float DTdkfl) {
		this.DTdkfl = DTdkfl;
	}

	public Integer getMCzrk() {
		return this.MCzrk;
	}

	public void setMCzrk(Integer MCzrk) {
		this.MCzrk = MCzrk;
	}

	public Integer getDCzrk() {
		return this.DCzrk;
	}

	public void setDCzrk(Integer DCzrk) {
		this.DCzrk = DCzrk;
	}

	public Float getMGdzctzze() {
		return this.MGdzctzze;
	}

	public void setMGdzctzze(Float MGdzctzze) {
		this.MGdzctzze = MGdzctzze;
	}

	public Float getDGdzctzze() {
		return this.DGdzctzze;
	}

	public void setDGdzctzze(Float DGdzctzze) {
		this.DGdzctzze = DGdzctzze;
	}

	public Float getMEscyssze() {
		return this.MEscyssze;
	}

	public void setMEscyssze(Float MEscyssze) {
		this.MEscyssze = MEscyssze;
	}

	public Float getDEscyssze() {
		return this.DEscyssze;
	}

	public void setDEscyssze(Float DEscyssze) {
		this.DEscyssze = DEscyssze;
	}

	public Float getMGyzsr() {
		return this.MGyzsr;
	}

	public void setMGyzsr(Float MGyzsr) {
		this.MGyzsr = MGyzsr;
	}

	public Float getDGyzsr() {
		return this.DGyzsr;
	}

	public void setDGyzsr(Float DGyzsr) {
		this.DGyzsr = DGyzsr;
	}

	public Float getMGyssze() {
		return this.MGyssze;
	}

	public void setMGyssze(Float MGyssze) {
		this.MGyssze = MGyssze;
	}

	public Float getDGyssze() {
		return this.DGyssze;
	}

	public void setDGyssze(Float DGyssze) {
		this.DGyssze = DGyssze;
	}

	public Float getMGxzsr() {
		return this.MGxzsr;
	}

	public void setMGxzsr(Float MGxzsr) {
		this.MGxzsr = MGxzsr;
	}

	public Float getDGxzsr() {
		return this.DGxzsr;
	}

	public void setDGxzsr(Float DGxzsr) {
		this.DGxzsr = DGxzsr;
	}

	public Float getMGxssze() {
		return this.MGxssze;
	}

	public void setMGxssze(Float MGxssze) {
		this.MGxssze = MGxssze;
	}

	public Float getDGxssze() {
		return this.DGxssze;
	}

	public void setDGxssze(Float DGxssze) {
		this.DGxssze = DGxssze;
	}

	public String getMXm() {
		return this.MXm;
	}

	public void setMXm(String MXm) {
		this.MXm = MXm;
	}

	public String getMKqtzsj() {
		return this.MKqtzsj;
	}

	public void setMKqtzsj(String MKqtzsj) {
		this.MKqtzsj = MKqtzsj;
	}

	public Float getMKqtzmj() {
		return this.MKqtzmj;
	}

	public void setMKqtzmj(Float MKqtzmj) {
		this.MKqtzmj = MKqtzmj;
	}

	public Float getMKqtzhmj() {
		return this.MKqtzhmj;
	}

	public void setMKqtzhmj(Float MKqtzhmj) {
		this.MKqtzhmj = MKqtzhmj;
	}

	public String getBz() {
		return this.bz;
	}

	public void setBz(String bz) {
		this.bz = bz;
	}

}
