package cn.mutu.land.model;

// Generated 2015-6-16 15:49:27 by Hibernate Tools 4.0.0

/**
 * LanduseIndexWeight generated by hbm2java
 */
public class LanduseIndexWeight implements java.io.Serializable {

	private Integer id;
	private String projectId;
	private String kfqName;
	private String kfqType;
	private String markType;
	private Float mainDevelopSum;
	private Float mainArea;
	private Float mainLanduse;
	private Float mainLanduseDegree;
	private Float mainLanduseDegreeSupply;
	private String mainLanduseDegreeSupplyReason;
	private Float mainLanduseDegreeBuild;
	private String mainLanduseDegreeBuildReason;
	private Float mainLanduseConstruct;
	private Float mainLanduseConstructIndustry;
	private String mainLanduseConstructIndustryReason;
	private Float mainLanduseIntensity;
	private Float mainLanduseIntensityRatio;
	private String mainLanduseIntensityRatioReason;
	private Float mainLanduseIntensityDensity;
	private String mainLanduseIntensityDensityReason;
	private Float mainLanduseIntensitySumratio;
	private String mainLanduseIntensitySumratioReason;
	private Float mainLanduseIntensityBuildindex;
	private String mainLanduseIntensityBuildindexReason;
	private Float mainBenefit;
	private Float mainBenefitInexport;
	private Float mainBenefitInexportAssets;
	private String mainBenefitInexportAssetsReason;
	private Float mainBenefitInexportTax;
	private String mainBenefitInexportTaxReason;
	private Float mainBenefitInexportPopulation;
	private String mainBenefitInexportPopulationReason;
	private Float mainPerformance;
	private Float mainPerformanceManage;
	private Float mainPerformanceManageIdle;
	private String mainPerformanceManageIdleReason;
	private Float developArea;
	private Float developLanduse;
	private Float developLanduseDegree;
	private Float developLanduseDegreeDevratio;
	private String developLanduseDegreeDevratioReason;
	private Float developLanduseConstruct;
	private Float developLanduseConstructIndustry;
	private String developLanduseConstructIndustryReason;
	private Float developLanduseIntensity;
	private Float developLanduseIntensityRatio;
	private String developLanduseIntensityRatioReason;
	private Float developLanduseIntensityDensity;
	private String developLanduseIntensityDensityReason;
	private Float developLanduseIntensitySumratio;
	private String developLanduseIntensitySumratioReason;
	private Float developLanduseIntensityBuildindex;
	private String developLanduseIntensityBuildindexReason;
	private Float developBenefit;
	private Float developBenefitInexport;
	private Float developBenefitInexportAssets;
	private String developBenefitInexportAssetsReason;
	private Float developBenefitInexportTax;
	private String developBenefitInexportTaxReason;
	private Float developBenefitInexportPopulation;
	private String developBenefitInexportPopulationReason;
	private Float developPerformance;
	private Float developPerformanceManage;
	private Float developPerformanceManageIdle;
	private String developPerformanceManageIdleReason;

	public LanduseIndexWeight() {
	}

	public LanduseIndexWeight(String projectId, String kfqName, String kfqType,
			String markType, Float mainDevelopSum, Float mainArea,
			Float mainLanduse, Float mainLanduseDegree,
			Float mainLanduseDegreeSupply,
			String mainLanduseDegreeSupplyReason, Float mainLanduseDegreeBuild,
			String mainLanduseDegreeBuildReason, Float mainLanduseConstruct,
			Float mainLanduseConstructIndustry,
			String mainLanduseConstructIndustryReason,
			Float mainLanduseIntensity, Float mainLanduseIntensityRatio,
			String mainLanduseIntensityRatioReason,
			Float mainLanduseIntensityDensity,
			String mainLanduseIntensityDensityReason,
			Float mainLanduseIntensitySumratio,
			String mainLanduseIntensitySumratioReason,
			Float mainLanduseIntensityBuildindex,
			String mainLanduseIntensityBuildindexReason, Float mainBenefit,
			Float mainBenefitInexport, Float mainBenefitInexportAssets,
			String mainBenefitInexportAssetsReason,
			Float mainBenefitInexportTax, String mainBenefitInexportTaxReason,
			Float mainBenefitInexportPopulation,
			String mainBenefitInexportPopulationReason, Float mainPerformance,
			Float mainPerformanceManage, Float mainPerformanceManageIdle,
			String mainPerformanceManageIdleReason, Float developArea,
			Float developLanduse, Float developLanduseDegree,
			Float developLanduseDegreeDevratio,
			String developLanduseDegreeDevratioReason,
			Float developLanduseConstruct,
			Float developLanduseConstructIndustry,
			String developLanduseConstructIndustryReason,
			Float developLanduseIntensity, Float developLanduseIntensityRatio,
			String developLanduseIntensityRatioReason,
			Float developLanduseIntensityDensity,
			String developLanduseIntensityDensityReason,
			Float developLanduseIntensitySumratio,
			String developLanduseIntensitySumratioReason,
			Float developLanduseIntensityBuildindex,
			String developLanduseIntensityBuildindexReason,
			Float developBenefit, Float developBenefitInexport,
			Float developBenefitInexportAssets,
			String developBenefitInexportAssetsReason,
			Float developBenefitInexportTax,
			String developBenefitInexportTaxReason,
			Float developBenefitInexportPopulation,
			String developBenefitInexportPopulationReason,
			Float developPerformance, Float developPerformanceManage,
			Float developPerformanceManageIdle,
			String developPerformanceManageIdleReason) {
		this.projectId = projectId;
		this.kfqName = kfqName;
		this.kfqType = kfqType;
		this.markType = markType;
		this.mainDevelopSum = mainDevelopSum;
		this.mainArea = mainArea;
		this.mainLanduse = mainLanduse;
		this.mainLanduseDegree = mainLanduseDegree;
		this.mainLanduseDegreeSupply = mainLanduseDegreeSupply;
		this.mainLanduseDegreeSupplyReason = mainLanduseDegreeSupplyReason;
		this.mainLanduseDegreeBuild = mainLanduseDegreeBuild;
		this.mainLanduseDegreeBuildReason = mainLanduseDegreeBuildReason;
		this.mainLanduseConstruct = mainLanduseConstruct;
		this.mainLanduseConstructIndustry = mainLanduseConstructIndustry;
		this.mainLanduseConstructIndustryReason = mainLanduseConstructIndustryReason;
		this.mainLanduseIntensity = mainLanduseIntensity;
		this.mainLanduseIntensityRatio = mainLanduseIntensityRatio;
		this.mainLanduseIntensityRatioReason = mainLanduseIntensityRatioReason;
		this.mainLanduseIntensityDensity = mainLanduseIntensityDensity;
		this.mainLanduseIntensityDensityReason = mainLanduseIntensityDensityReason;
		this.mainLanduseIntensitySumratio = mainLanduseIntensitySumratio;
		this.mainLanduseIntensitySumratioReason = mainLanduseIntensitySumratioReason;
		this.mainLanduseIntensityBuildindex = mainLanduseIntensityBuildindex;
		this.mainLanduseIntensityBuildindexReason = mainLanduseIntensityBuildindexReason;
		this.mainBenefit = mainBenefit;
		this.mainBenefitInexport = mainBenefitInexport;
		this.mainBenefitInexportAssets = mainBenefitInexportAssets;
		this.mainBenefitInexportAssetsReason = mainBenefitInexportAssetsReason;
		this.mainBenefitInexportTax = mainBenefitInexportTax;
		this.mainBenefitInexportTaxReason = mainBenefitInexportTaxReason;
		this.mainBenefitInexportPopulation = mainBenefitInexportPopulation;
		this.mainBenefitInexportPopulationReason = mainBenefitInexportPopulationReason;
		this.mainPerformance = mainPerformance;
		this.mainPerformanceManage = mainPerformanceManage;
		this.mainPerformanceManageIdle = mainPerformanceManageIdle;
		this.mainPerformanceManageIdleReason = mainPerformanceManageIdleReason;
		this.developArea = developArea;
		this.developLanduse = developLanduse;
		this.developLanduseDegree = developLanduseDegree;
		this.developLanduseDegreeDevratio = developLanduseDegreeDevratio;
		this.developLanduseDegreeDevratioReason = developLanduseDegreeDevratioReason;
		this.developLanduseConstruct = developLanduseConstruct;
		this.developLanduseConstructIndustry = developLanduseConstructIndustry;
		this.developLanduseConstructIndustryReason = developLanduseConstructIndustryReason;
		this.developLanduseIntensity = developLanduseIntensity;
		this.developLanduseIntensityRatio = developLanduseIntensityRatio;
		this.developLanduseIntensityRatioReason = developLanduseIntensityRatioReason;
		this.developLanduseIntensityDensity = developLanduseIntensityDensity;
		this.developLanduseIntensityDensityReason = developLanduseIntensityDensityReason;
		this.developLanduseIntensitySumratio = developLanduseIntensitySumratio;
		this.developLanduseIntensitySumratioReason = developLanduseIntensitySumratioReason;
		this.developLanduseIntensityBuildindex = developLanduseIntensityBuildindex;
		this.developLanduseIntensityBuildindexReason = developLanduseIntensityBuildindexReason;
		this.developBenefit = developBenefit;
		this.developBenefitInexport = developBenefitInexport;
		this.developBenefitInexportAssets = developBenefitInexportAssets;
		this.developBenefitInexportAssetsReason = developBenefitInexportAssetsReason;
		this.developBenefitInexportTax = developBenefitInexportTax;
		this.developBenefitInexportTaxReason = developBenefitInexportTaxReason;
		this.developBenefitInexportPopulation = developBenefitInexportPopulation;
		this.developBenefitInexportPopulationReason = developBenefitInexportPopulationReason;
		this.developPerformance = developPerformance;
		this.developPerformanceManage = developPerformanceManage;
		this.developPerformanceManageIdle = developPerformanceManageIdle;
		this.developPerformanceManageIdleReason = developPerformanceManageIdleReason;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getProjectId() {
		return this.projectId;
	}

	public void setProjectId(String projectId) {
		this.projectId = projectId;
	}

	public String getKfqName() {
		return this.kfqName;
	}

	public void setKfqName(String kfqName) {
		this.kfqName = kfqName;
	}

	public String getKfqType() {
		return this.kfqType;
	}

	public void setKfqType(String kfqType) {
		this.kfqType = kfqType;
	}

	public String getMarkType() {
		return this.markType;
	}

	public void setMarkType(String markType) {
		this.markType = markType;
	}

	public Float getMainDevelopSum() {
		return this.mainDevelopSum;
	}

	public void setMainDevelopSum(Float mainDevelopSum) {
		this.mainDevelopSum = mainDevelopSum;
	}

	public Float getMainArea() {
		return this.mainArea;
	}

	public void setMainArea(Float mainArea) {
		this.mainArea = mainArea;
	}

	public Float getMainLanduse() {
		return this.mainLanduse;
	}

	public void setMainLanduse(Float mainLanduse) {
		this.mainLanduse = mainLanduse;
	}

	public Float getMainLanduseDegree() {
		return this.mainLanduseDegree;
	}

	public void setMainLanduseDegree(Float mainLanduseDegree) {
		this.mainLanduseDegree = mainLanduseDegree;
	}

	public Float getMainLanduseDegreeSupply() {
		return this.mainLanduseDegreeSupply;
	}

	public void setMainLanduseDegreeSupply(Float mainLanduseDegreeSupply) {
		this.mainLanduseDegreeSupply = mainLanduseDegreeSupply;
	}

	public String getMainLanduseDegreeSupplyReason() {
		return this.mainLanduseDegreeSupplyReason;
	}

	public void setMainLanduseDegreeSupplyReason(
			String mainLanduseDegreeSupplyReason) {
		this.mainLanduseDegreeSupplyReason = mainLanduseDegreeSupplyReason;
	}

	public Float getMainLanduseDegreeBuild() {
		return this.mainLanduseDegreeBuild;
	}

	public void setMainLanduseDegreeBuild(Float mainLanduseDegreeBuild) {
		this.mainLanduseDegreeBuild = mainLanduseDegreeBuild;
	}

	public String getMainLanduseDegreeBuildReason() {
		return this.mainLanduseDegreeBuildReason;
	}

	public void setMainLanduseDegreeBuildReason(
			String mainLanduseDegreeBuildReason) {
		this.mainLanduseDegreeBuildReason = mainLanduseDegreeBuildReason;
	}

	public Float getMainLanduseConstruct() {
		return this.mainLanduseConstruct;
	}

	public void setMainLanduseConstruct(Float mainLanduseConstruct) {
		this.mainLanduseConstruct = mainLanduseConstruct;
	}

	public Float getMainLanduseConstructIndustry() {
		return this.mainLanduseConstructIndustry;
	}

	public void setMainLanduseConstructIndustry(
			Float mainLanduseConstructIndustry) {
		this.mainLanduseConstructIndustry = mainLanduseConstructIndustry;
	}

	public String getMainLanduseConstructIndustryReason() {
		return this.mainLanduseConstructIndustryReason;
	}

	public void setMainLanduseConstructIndustryReason(
			String mainLanduseConstructIndustryReason) {
		this.mainLanduseConstructIndustryReason = mainLanduseConstructIndustryReason;
	}

	public Float getMainLanduseIntensity() {
		return this.mainLanduseIntensity;
	}

	public void setMainLanduseIntensity(Float mainLanduseIntensity) {
		this.mainLanduseIntensity = mainLanduseIntensity;
	}

	public Float getMainLanduseIntensityRatio() {
		return this.mainLanduseIntensityRatio;
	}

	public void setMainLanduseIntensityRatio(Float mainLanduseIntensityRatio) {
		this.mainLanduseIntensityRatio = mainLanduseIntensityRatio;
	}

	public String getMainLanduseIntensityRatioReason() {
		return this.mainLanduseIntensityRatioReason;
	}

	public void setMainLanduseIntensityRatioReason(
			String mainLanduseIntensityRatioReason) {
		this.mainLanduseIntensityRatioReason = mainLanduseIntensityRatioReason;
	}

	public Float getMainLanduseIntensityDensity() {
		return this.mainLanduseIntensityDensity;
	}

	public void setMainLanduseIntensityDensity(Float mainLanduseIntensityDensity) {
		this.mainLanduseIntensityDensity = mainLanduseIntensityDensity;
	}

	public String getMainLanduseIntensityDensityReason() {
		return this.mainLanduseIntensityDensityReason;
	}

	public void setMainLanduseIntensityDensityReason(
			String mainLanduseIntensityDensityReason) {
		this.mainLanduseIntensityDensityReason = mainLanduseIntensityDensityReason;
	}

	public Float getMainLanduseIntensitySumratio() {
		return this.mainLanduseIntensitySumratio;
	}

	public void setMainLanduseIntensitySumratio(
			Float mainLanduseIntensitySumratio) {
		this.mainLanduseIntensitySumratio = mainLanduseIntensitySumratio;
	}

	public String getMainLanduseIntensitySumratioReason() {
		return this.mainLanduseIntensitySumratioReason;
	}

	public void setMainLanduseIntensitySumratioReason(
			String mainLanduseIntensitySumratioReason) {
		this.mainLanduseIntensitySumratioReason = mainLanduseIntensitySumratioReason;
	}

	public Float getMainLanduseIntensityBuildindex() {
		return this.mainLanduseIntensityBuildindex;
	}

	public void setMainLanduseIntensityBuildindex(
			Float mainLanduseIntensityBuildindex) {
		this.mainLanduseIntensityBuildindex = mainLanduseIntensityBuildindex;
	}

	public String getMainLanduseIntensityBuildindexReason() {
		return this.mainLanduseIntensityBuildindexReason;
	}

	public void setMainLanduseIntensityBuildindexReason(
			String mainLanduseIntensityBuildindexReason) {
		this.mainLanduseIntensityBuildindexReason = mainLanduseIntensityBuildindexReason;
	}

	public Float getMainBenefit() {
		return this.mainBenefit;
	}

	public void setMainBenefit(Float mainBenefit) {
		this.mainBenefit = mainBenefit;
	}

	public Float getMainBenefitInexport() {
		return this.mainBenefitInexport;
	}

	public void setMainBenefitInexport(Float mainBenefitInexport) {
		this.mainBenefitInexport = mainBenefitInexport;
	}

	public Float getMainBenefitInexportAssets() {
		return this.mainBenefitInexportAssets;
	}

	public void setMainBenefitInexportAssets(Float mainBenefitInexportAssets) {
		this.mainBenefitInexportAssets = mainBenefitInexportAssets;
	}

	public String getMainBenefitInexportAssetsReason() {
		return this.mainBenefitInexportAssetsReason;
	}

	public void setMainBenefitInexportAssetsReason(
			String mainBenefitInexportAssetsReason) {
		this.mainBenefitInexportAssetsReason = mainBenefitInexportAssetsReason;
	}

	public Float getMainBenefitInexportTax() {
		return this.mainBenefitInexportTax;
	}

	public void setMainBenefitInexportTax(Float mainBenefitInexportTax) {
		this.mainBenefitInexportTax = mainBenefitInexportTax;
	}

	public String getMainBenefitInexportTaxReason() {
		return this.mainBenefitInexportTaxReason;
	}

	public void setMainBenefitInexportTaxReason(
			String mainBenefitInexportTaxReason) {
		this.mainBenefitInexportTaxReason = mainBenefitInexportTaxReason;
	}

	public Float getMainBenefitInexportPopulation() {
		return this.mainBenefitInexportPopulation;
	}

	public void setMainBenefitInexportPopulation(
			Float mainBenefitInexportPopulation) {
		this.mainBenefitInexportPopulation = mainBenefitInexportPopulation;
	}

	public String getMainBenefitInexportPopulationReason() {
		return this.mainBenefitInexportPopulationReason;
	}

	public void setMainBenefitInexportPopulationReason(
			String mainBenefitInexportPopulationReason) {
		this.mainBenefitInexportPopulationReason = mainBenefitInexportPopulationReason;
	}

	public Float getMainPerformance() {
		return this.mainPerformance;
	}

	public void setMainPerformance(Float mainPerformance) {
		this.mainPerformance = mainPerformance;
	}

	public Float getMainPerformanceManage() {
		return this.mainPerformanceManage;
	}

	public void setMainPerformanceManage(Float mainPerformanceManage) {
		this.mainPerformanceManage = mainPerformanceManage;
	}

	public Float getMainPerformanceManageIdle() {
		return this.mainPerformanceManageIdle;
	}

	public void setMainPerformanceManageIdle(Float mainPerformanceManageIdle) {
		this.mainPerformanceManageIdle = mainPerformanceManageIdle;
	}

	public String getMainPerformanceManageIdleReason() {
		return this.mainPerformanceManageIdleReason;
	}

	public void setMainPerformanceManageIdleReason(
			String mainPerformanceManageIdleReason) {
		this.mainPerformanceManageIdleReason = mainPerformanceManageIdleReason;
	}

	public Float getDevelopArea() {
		return this.developArea;
	}

	public void setDevelopArea(Float developArea) {
		this.developArea = developArea;
	}

	public Float getDevelopLanduse() {
		return this.developLanduse;
	}

	public void setDevelopLanduse(Float developLanduse) {
		this.developLanduse = developLanduse;
	}

	public Float getDevelopLanduseDegree() {
		return this.developLanduseDegree;
	}

	public void setDevelopLanduseDegree(Float developLanduseDegree) {
		this.developLanduseDegree = developLanduseDegree;
	}

	public Float getDevelopLanduseDegreeDevratio() {
		return this.developLanduseDegreeDevratio;
	}

	public void setDevelopLanduseDegreeDevratio(
			Float developLanduseDegreeDevratio) {
		this.developLanduseDegreeDevratio = developLanduseDegreeDevratio;
	}

	public String getDevelopLanduseDegreeDevratioReason() {
		return this.developLanduseDegreeDevratioReason;
	}

	public void setDevelopLanduseDegreeDevratioReason(
			String developLanduseDegreeDevratioReason) {
		this.developLanduseDegreeDevratioReason = developLanduseDegreeDevratioReason;
	}

	public Float getDevelopLanduseConstruct() {
		return this.developLanduseConstruct;
	}

	public void setDevelopLanduseConstruct(Float developLanduseConstruct) {
		this.developLanduseConstruct = developLanduseConstruct;
	}

	public Float getDevelopLanduseConstructIndustry() {
		return this.developLanduseConstructIndustry;
	}

	public void setDevelopLanduseConstructIndustry(
			Float developLanduseConstructIndustry) {
		this.developLanduseConstructIndustry = developLanduseConstructIndustry;
	}

	public String getDevelopLanduseConstructIndustryReason() {
		return this.developLanduseConstructIndustryReason;
	}

	public void setDevelopLanduseConstructIndustryReason(
			String developLanduseConstructIndustryReason) {
		this.developLanduseConstructIndustryReason = developLanduseConstructIndustryReason;
	}

	public Float getDevelopLanduseIntensity() {
		return this.developLanduseIntensity;
	}

	public void setDevelopLanduseIntensity(Float developLanduseIntensity) {
		this.developLanduseIntensity = developLanduseIntensity;
	}

	public Float getDevelopLanduseIntensityRatio() {
		return this.developLanduseIntensityRatio;
	}

	public void setDevelopLanduseIntensityRatio(
			Float developLanduseIntensityRatio) {
		this.developLanduseIntensityRatio = developLanduseIntensityRatio;
	}

	public String getDevelopLanduseIntensityRatioReason() {
		return this.developLanduseIntensityRatioReason;
	}

	public void setDevelopLanduseIntensityRatioReason(
			String developLanduseIntensityRatioReason) {
		this.developLanduseIntensityRatioReason = developLanduseIntensityRatioReason;
	}

	public Float getDevelopLanduseIntensityDensity() {
		return this.developLanduseIntensityDensity;
	}

	public void setDevelopLanduseIntensityDensity(
			Float developLanduseIntensityDensity) {
		this.developLanduseIntensityDensity = developLanduseIntensityDensity;
	}

	public String getDevelopLanduseIntensityDensityReason() {
		return this.developLanduseIntensityDensityReason;
	}

	public void setDevelopLanduseIntensityDensityReason(
			String developLanduseIntensityDensityReason) {
		this.developLanduseIntensityDensityReason = developLanduseIntensityDensityReason;
	}

	public Float getDevelopLanduseIntensitySumratio() {
		return this.developLanduseIntensitySumratio;
	}

	public void setDevelopLanduseIntensitySumratio(
			Float developLanduseIntensitySumratio) {
		this.developLanduseIntensitySumratio = developLanduseIntensitySumratio;
	}

	public String getDevelopLanduseIntensitySumratioReason() {
		return this.developLanduseIntensitySumratioReason;
	}

	public void setDevelopLanduseIntensitySumratioReason(
			String developLanduseIntensitySumratioReason) {
		this.developLanduseIntensitySumratioReason = developLanduseIntensitySumratioReason;
	}

	public Float getDevelopLanduseIntensityBuildindex() {
		return this.developLanduseIntensityBuildindex;
	}

	public void setDevelopLanduseIntensityBuildindex(
			Float developLanduseIntensityBuildindex) {
		this.developLanduseIntensityBuildindex = developLanduseIntensityBuildindex;
	}

	public String getDevelopLanduseIntensityBuildindexReason() {
		return this.developLanduseIntensityBuildindexReason;
	}

	public void setDevelopLanduseIntensityBuildindexReason(
			String developLanduseIntensityBuildindexReason) {
		this.developLanduseIntensityBuildindexReason = developLanduseIntensityBuildindexReason;
	}

	public Float getDevelopBenefit() {
		return this.developBenefit;
	}

	public void setDevelopBenefit(Float developBenefit) {
		this.developBenefit = developBenefit;
	}

	public Float getDevelopBenefitInexport() {
		return this.developBenefitInexport;
	}

	public void setDevelopBenefitInexport(Float developBenefitInexport) {
		this.developBenefitInexport = developBenefitInexport;
	}

	public Float getDevelopBenefitInexportAssets() {
		return this.developBenefitInexportAssets;
	}

	public void setDevelopBenefitInexportAssets(
			Float developBenefitInexportAssets) {
		this.developBenefitInexportAssets = developBenefitInexportAssets;
	}

	public String getDevelopBenefitInexportAssetsReason() {
		return this.developBenefitInexportAssetsReason;
	}

	public void setDevelopBenefitInexportAssetsReason(
			String developBenefitInexportAssetsReason) {
		this.developBenefitInexportAssetsReason = developBenefitInexportAssetsReason;
	}

	public Float getDevelopBenefitInexportTax() {
		return this.developBenefitInexportTax;
	}

	public void setDevelopBenefitInexportTax(Float developBenefitInexportTax) {
		this.developBenefitInexportTax = developBenefitInexportTax;
	}

	public String getDevelopBenefitInexportTaxReason() {
		return this.developBenefitInexportTaxReason;
	}

	public void setDevelopBenefitInexportTaxReason(
			String developBenefitInexportTaxReason) {
		this.developBenefitInexportTaxReason = developBenefitInexportTaxReason;
	}

	public Float getDevelopBenefitInexportPopulation() {
		return this.developBenefitInexportPopulation;
	}

	public void setDevelopBenefitInexportPopulation(
			Float developBenefitInexportPopulation) {
		this.developBenefitInexportPopulation = developBenefitInexportPopulation;
	}

	public String getDevelopBenefitInexportPopulationReason() {
		return this.developBenefitInexportPopulationReason;
	}

	public void setDevelopBenefitInexportPopulationReason(
			String developBenefitInexportPopulationReason) {
		this.developBenefitInexportPopulationReason = developBenefitInexportPopulationReason;
	}

	public Float getDevelopPerformance() {
		return this.developPerformance;
	}

	public void setDevelopPerformance(Float developPerformance) {
		this.developPerformance = developPerformance;
	}

	public Float getDevelopPerformanceManage() {
		return this.developPerformanceManage;
	}

	public void setDevelopPerformanceManage(Float developPerformanceManage) {
		this.developPerformanceManage = developPerformanceManage;
	}

	public Float getDevelopPerformanceManageIdle() {
		return this.developPerformanceManageIdle;
	}

	public void setDevelopPerformanceManageIdle(
			Float developPerformanceManageIdle) {
		this.developPerformanceManageIdle = developPerformanceManageIdle;
	}

	public String getDevelopPerformanceManageIdleReason() {
		return this.developPerformanceManageIdleReason;
	}

	public void setDevelopPerformanceManageIdleReason(
			String developPerformanceManageIdleReason) {
		this.developPerformanceManageIdleReason = developPerformanceManageIdleReason;
	}

}
