package cn.mutu.land.model;

// Generated 2015-6-18 16:06:26 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * LanduseIntensityManager generated by hbm2java
 */
public class LanduseIntensityManager implements java.io.Serializable {

	private Integer id;
	private String kfqName;
	private String kfqMap;
	private Date calcDate;
	private Double mainExpire;
	private Double mainIdeal;
	private Double developExpire;
	private Double developIdeal;
	private Double sumExpire;
	private Double sumIdeal;

	public LanduseIntensityManager() {
	}

	public LanduseIntensityManager(String kfqName, String kfqMap,
			Date calcDate, Double mainExpire, Double mainIdeal,
			Double developExpire, Double developIdeal, Double sumExpire,
			Double sumIdeal) {
		this.kfqName = kfqName;
		this.kfqMap = kfqMap;
		this.calcDate = calcDate;
		this.mainExpire = mainExpire;
		this.mainIdeal = mainIdeal;
		this.developExpire = developExpire;
		this.developIdeal = developIdeal;
		this.sumExpire = sumExpire;
		this.sumIdeal = sumIdeal;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getKfqName() {
		return this.kfqName;
	}

	public void setKfqName(String kfqName) {
		this.kfqName = kfqName;
	}

	public String getKfqMap() {
		return this.kfqMap;
	}

	public void setKfqMap(String kfqMap) {
		this.kfqMap = kfqMap;
	}

	public Date getCalcDate() {
		return this.calcDate;
	}

	public void setCalcDate(Date calcDate) {
		this.calcDate = calcDate;
	}

	public Double getMainExpire() {
		return this.mainExpire;
	}

	public void setMainExpire(Double mainExpire) {
		this.mainExpire = mainExpire;
	}

	public Double getMainIdeal() {
		return this.mainIdeal;
	}

	public void setMainIdeal(Double mainIdeal) {
		this.mainIdeal = mainIdeal;
	}

	public Double getDevelopExpire() {
		return this.developExpire;
	}

	public void setDevelopExpire(Double developExpire) {
		this.developExpire = developExpire;
	}

	public Double getDevelopIdeal() {
		return this.developIdeal;
	}

	public void setDevelopIdeal(Double developIdeal) {
		this.developIdeal = developIdeal;
	}

	public Double getSumExpire() {
		return this.sumExpire;
	}

	public void setSumExpire(Double sumExpire) {
		this.sumExpire = sumExpire;
	}

	public Double getSumIdeal() {
		return this.sumIdeal;
	}

	public void setSumIdeal(Double sumIdeal) {
		this.sumIdeal = sumIdeal;
	}

}
