package cn.mutu.land.model;

// Generated 2015-6-17 9:22:50 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * LanduseIntensityIntension generated by hbm2java
 */
public class LanduseIntensityIntension implements java.io.Serializable {

	private Integer id;
	private String kfqName;
	private String kfqMap;
	private Date calcDate;
	private Double dldmGkccmj;
	private Double mainSumratioWeight;
	private Double mainSumratioIdeal;
	private Double mainSumratioIntension;
	private Double mainBuildrateWeight;
	private Double mainBuildrateIdeal;
	private Double mainBuildrateIntension;
	private Double mainAssetWeight;
	private Double mainAssetIdeal;
	private Double mainAssetIntension;
	private Double mainTaxWeight;
	private Double mainTaxIdeal;
	private Double mainTaxIntension;
	private Double mainSumtaxWeight;
	private Double mainSumtaxIdeal;
	private Double mainSumtaxIntension;
	private Double developSumratioWeight;
	private Double developSumratioIdeal;
	private Double developSumratioIntension;
	private Double developBuildrateWeight;
	private Double developBuildrateIdeal;
	private Double developBuildrateIntension;
	private Double developAssetWeight;
	private Double developAssetIdeal;
	private Double developAssetIntension;
	private Double developTaxWeight;
	private Double developTaxIdeal;
	private Double developTaxIntension;
	private Double developSumtaxWeight;
	private Double developSumtaxIdeal;
	private Double developSumtaxIntension;

	public LanduseIntensityIntension() {
	}

	public LanduseIntensityIntension(String kfqName, String kfqMap,
			Date calcDate, Double dldmGkccmj, Double mainSumratioWeight,
			Double mainSumratioIdeal, Double mainSumratioIntension,
			Double mainBuildrateWeight, Double mainBuildrateIdeal,
			Double mainBuildrateIntension, Double mainAssetWeight,
			Double mainAssetIdeal, Double mainAssetIntension,
			Double mainTaxWeight, Double mainTaxIdeal, Double mainTaxIntension,
			Double mainSumtaxWeight, Double mainSumtaxIdeal,
			Double mainSumtaxIntension, Double developSumratioWeight,
			Double developSumratioIdeal, Double developSumratioIntension,
			Double developBuildrateWeight, Double developBuildrateIdeal,
			Double developBuildrateIntension, Double developAssetWeight,
			Double developAssetIdeal, Double developAssetIntension,
			Double developTaxWeight, Double developTaxIdeal,
			Double developTaxIntension, Double developSumtaxWeight,
			Double developSumtaxIdeal, Double developSumtaxIntension) {
		this.kfqName = kfqName;
		this.kfqMap = kfqMap;
		this.calcDate = calcDate;
		this.dldmGkccmj = dldmGkccmj;
		this.mainSumratioWeight = mainSumratioWeight;
		this.mainSumratioIdeal = mainSumratioIdeal;
		this.mainSumratioIntension = mainSumratioIntension;
		this.mainBuildrateWeight = mainBuildrateWeight;
		this.mainBuildrateIdeal = mainBuildrateIdeal;
		this.mainBuildrateIntension = mainBuildrateIntension;
		this.mainAssetWeight = mainAssetWeight;
		this.mainAssetIdeal = mainAssetIdeal;
		this.mainAssetIntension = mainAssetIntension;
		this.mainTaxWeight = mainTaxWeight;
		this.mainTaxIdeal = mainTaxIdeal;
		this.mainTaxIntension = mainTaxIntension;
		this.mainSumtaxWeight = mainSumtaxWeight;
		this.mainSumtaxIdeal = mainSumtaxIdeal;
		this.mainSumtaxIntension = mainSumtaxIntension;
		this.developSumratioWeight = developSumratioWeight;
		this.developSumratioIdeal = developSumratioIdeal;
		this.developSumratioIntension = developSumratioIntension;
		this.developBuildrateWeight = developBuildrateWeight;
		this.developBuildrateIdeal = developBuildrateIdeal;
		this.developBuildrateIntension = developBuildrateIntension;
		this.developAssetWeight = developAssetWeight;
		this.developAssetIdeal = developAssetIdeal;
		this.developAssetIntension = developAssetIntension;
		this.developTaxWeight = developTaxWeight;
		this.developTaxIdeal = developTaxIdeal;
		this.developTaxIntension = developTaxIntension;
		this.developSumtaxWeight = developSumtaxWeight;
		this.developSumtaxIdeal = developSumtaxIdeal;
		this.developSumtaxIntension = developSumtaxIntension;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getKfqName() {
		return this.kfqName;
	}

	public void setKfqName(String kfqName) {
		this.kfqName = kfqName;
	}

	public String getKfqMap() {
		return this.kfqMap;
	}

	public void setKfqMap(String kfqMap) {
		this.kfqMap = kfqMap;
	}

	public Date getCalcDate() {
		return this.calcDate;
	}

	public void setCalcDate(Date calcDate) {
		this.calcDate = calcDate;
	}

	public Double getDldmGkccmj() {
		return this.dldmGkccmj;
	}

	public void setDldmGkccmj(Double dldmGkccmj) {
		this.dldmGkccmj = dldmGkccmj;
	}

	public Double getMainSumratioWeight() {
		return this.mainSumratioWeight;
	}

	public void setMainSumratioWeight(Double mainSumratioWeight) {
		this.mainSumratioWeight = mainSumratioWeight;
	}

	public Double getMainSumratioIdeal() {
		return this.mainSumratioIdeal;
	}

	public void setMainSumratioIdeal(Double mainSumratioIdeal) {
		this.mainSumratioIdeal = mainSumratioIdeal;
	}

	public Double getMainSumratioIntension() {
		return this.mainSumratioIntension;
	}

	public void setMainSumratioIntension(Double mainSumratioIntension) {
		this.mainSumratioIntension = mainSumratioIntension;
	}

	public Double getMainBuildrateWeight() {
		return this.mainBuildrateWeight;
	}

	public void setMainBuildrateWeight(Double mainBuildrateWeight) {
		this.mainBuildrateWeight = mainBuildrateWeight;
	}

	public Double getMainBuildrateIdeal() {
		return this.mainBuildrateIdeal;
	}

	public void setMainBuildrateIdeal(Double mainBuildrateIdeal) {
		this.mainBuildrateIdeal = mainBuildrateIdeal;
	}

	public Double getMainBuildrateIntension() {
		return this.mainBuildrateIntension;
	}

	public void setMainBuildrateIntension(Double mainBuildrateIntension) {
		this.mainBuildrateIntension = mainBuildrateIntension;
	}

	public Double getMainAssetWeight() {
		return this.mainAssetWeight;
	}

	public void setMainAssetWeight(Double mainAssetWeight) {
		this.mainAssetWeight = mainAssetWeight;
	}

	public Double getMainAssetIdeal() {
		return this.mainAssetIdeal;
	}

	public void setMainAssetIdeal(Double mainAssetIdeal) {
		this.mainAssetIdeal = mainAssetIdeal;
	}

	public Double getMainAssetIntension() {
		return this.mainAssetIntension;
	}

	public void setMainAssetIntension(Double mainAssetIntension) {
		this.mainAssetIntension = mainAssetIntension;
	}

	public Double getMainTaxWeight() {
		return this.mainTaxWeight;
	}

	public void setMainTaxWeight(Double mainTaxWeight) {
		this.mainTaxWeight = mainTaxWeight;
	}

	public Double getMainTaxIdeal() {
		return this.mainTaxIdeal;
	}

	public void setMainTaxIdeal(Double mainTaxIdeal) {
		this.mainTaxIdeal = mainTaxIdeal;
	}

	public Double getMainTaxIntension() {
		return this.mainTaxIntension;
	}

	public void setMainTaxIntension(Double mainTaxIntension) {
		this.mainTaxIntension = mainTaxIntension;
	}

	public Double getMainSumtaxWeight() {
		return this.mainSumtaxWeight;
	}

	public void setMainSumtaxWeight(Double mainSumtaxWeight) {
		this.mainSumtaxWeight = mainSumtaxWeight;
	}

	public Double getMainSumtaxIdeal() {
		return this.mainSumtaxIdeal;
	}

	public void setMainSumtaxIdeal(Double mainSumtaxIdeal) {
		this.mainSumtaxIdeal = mainSumtaxIdeal;
	}

	public Double getMainSumtaxIntension() {
		return this.mainSumtaxIntension;
	}

	public void setMainSumtaxIntension(Double mainSumtaxIntension) {
		this.mainSumtaxIntension = mainSumtaxIntension;
	}

	public Double getDevelopSumratioWeight() {
		return this.developSumratioWeight;
	}

	public void setDevelopSumratioWeight(Double developSumratioWeight) {
		this.developSumratioWeight = developSumratioWeight;
	}

	public Double getDevelopSumratioIdeal() {
		return this.developSumratioIdeal;
	}

	public void setDevelopSumratioIdeal(Double developSumratioIdeal) {
		this.developSumratioIdeal = developSumratioIdeal;
	}

	public Double getDevelopSumratioIntension() {
		return this.developSumratioIntension;
	}

	public void setDevelopSumratioIntension(Double developSumratioIntension) {
		this.developSumratioIntension = developSumratioIntension;
	}

	public Double getDevelopBuildrateWeight() {
		return this.developBuildrateWeight;
	}

	public void setDevelopBuildrateWeight(Double developBuildrateWeight) {
		this.developBuildrateWeight = developBuildrateWeight;
	}

	public Double getDevelopBuildrateIdeal() {
		return this.developBuildrateIdeal;
	}

	public void setDevelopBuildrateIdeal(Double developBuildrateIdeal) {
		this.developBuildrateIdeal = developBuildrateIdeal;
	}

	public Double getDevelopBuildrateIntension() {
		return this.developBuildrateIntension;
	}

	public void setDevelopBuildrateIntension(Double developBuildrateIntension) {
		this.developBuildrateIntension = developBuildrateIntension;
	}

	public Double getDevelopAssetWeight() {
		return this.developAssetWeight;
	}

	public void setDevelopAssetWeight(Double developAssetWeight) {
		this.developAssetWeight = developAssetWeight;
	}

	public Double getDevelopAssetIdeal() {
		return this.developAssetIdeal;
	}

	public void setDevelopAssetIdeal(Double developAssetIdeal) {
		this.developAssetIdeal = developAssetIdeal;
	}

	public Double getDevelopAssetIntension() {
		return this.developAssetIntension;
	}

	public void setDevelopAssetIntension(Double developAssetIntension) {
		this.developAssetIntension = developAssetIntension;
	}

	public Double getDevelopTaxWeight() {
		return this.developTaxWeight;
	}

	public void setDevelopTaxWeight(Double developTaxWeight) {
		this.developTaxWeight = developTaxWeight;
	}

	public Double getDevelopTaxIdeal() {
		return this.developTaxIdeal;
	}

	public void setDevelopTaxIdeal(Double developTaxIdeal) {
		this.developTaxIdeal = developTaxIdeal;
	}

	public Double getDevelopTaxIntension() {
		return this.developTaxIntension;
	}

	public void setDevelopTaxIntension(Double developTaxIntension) {
		this.developTaxIntension = developTaxIntension;
	}

	public Double getDevelopSumtaxWeight() {
		return this.developSumtaxWeight;
	}

	public void setDevelopSumtaxWeight(Double developSumtaxWeight) {
		this.developSumtaxWeight = developSumtaxWeight;
	}

	public Double getDevelopSumtaxIdeal() {
		return this.developSumtaxIdeal;
	}

	public void setDevelopSumtaxIdeal(Double developSumtaxIdeal) {
		this.developSumtaxIdeal = developSumtaxIdeal;
	}

	public Double getDevelopSumtaxIntension() {
		return this.developSumtaxIntension;
	}

	public void setDevelopSumtaxIntension(Double developSumtaxIntension) {
		this.developSumtaxIntension = developSumtaxIntension;
	}

}
