package cn.mutu.land.model;

// Generated 2016-6-16 22:53:53 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * LawRegulation generated by hbm2java
 */
public class LawRegulation implements java.io.Serializable {

	private Integer id;
	private String lawType;
	private String lawTitle;
	private Date publishDate;
	private String publishDept;
	private String description;
	private String lawContent;
	private String lawEditor;
	private int readCount;

	public LawRegulation() {
	}

	public LawRegulation(int readCount) {
		this.readCount = readCount;
	}

	public LawRegulation(String lawType, String lawTitle, Date publishDate,
			String publishDept, String description, String lawContent,
			String lawEditor, int readCount) {
		this.lawType = lawType;
		this.lawTitle = lawTitle;
		this.publishDate = publishDate;
		this.publishDept = publishDept;
		this.description = description;
		this.lawContent = lawContent;
		this.lawEditor = lawEditor;
		this.readCount = readCount;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getLawType() {
		return this.lawType;
	}

	public void setLawType(String lawType) {
		this.lawType = lawType;
	}

	public String getLawTitle() {
		return this.lawTitle;
	}

	public void setLawTitle(String lawTitle) {
		this.lawTitle = lawTitle;
	}

	public Date getPublishDate() {
		return this.publishDate;
	}

	public void setPublishDate(Date publishDate) {
		this.publishDate = publishDate;
	}

	public String getPublishDept() {
		return this.publishDept;
	}

	public void setPublishDept(String publishDept) {
		this.publishDept = publishDept;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getLawContent() {
		return this.lawContent;
	}

	public void setLawContent(String lawContent) {
		this.lawContent = lawContent;
	}

	public String getLawEditor() {
		return this.lawEditor;
	}

	public void setLawEditor(String lawEditor) {
		this.lawEditor = lawEditor;
	}

	public int getReadCount() {
		return this.readCount;
	}

	public void setReadCount(int readCount) {
		this.readCount = readCount;
	}

}
