package cn.mutu.land.model;

// Generated 2015-6-8 20:28:03 by Hibernate Tools 4.0.0

/**
 * LawTypes generated by hbm2java
 */
public class LawTypes implements java.io.Serializable {

	private Integer id;
	private Integer pid;
	private String lawType;
	private String description;

	public LawTypes() {
	}

	public LawTypes(Integer pid, String lawType, String description) {
		this.pid = pid;
		this.lawType = lawType;
		this.description = description;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getPid() {
		return this.pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}

	public String getLawType() {
		return this.lawType;
	}

	public void setLawType(String lawType) {
		this.lawType = lawType;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
