package cn.mutu.land.model;

// Generated 2016-6-11 12:24:29 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * NoticeColumns generated by hbm2java
 */
@Entity
@Table(name = "notice_columns", catalog = "landuse")
public class NoticeColumns implements java.io.Serializable {

	private Integer id;
	private String columnName;
	private String description;

	public NoticeColumns() {
	}

	public NoticeColumns(String columnName, String description) {
		this.columnName = columnName;
		this.description = description;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "column_name", length = 50)
	public String getColumnName() {
		return this.columnName;
	}

	public void setColumnName(String columnName) {
		this.columnName = columnName;
	}

	@Column(name = "description", length = 200)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
