package cn.mutu.land.model;

// Generated 2015-6-3 20:23:59 by Hibernate Tools 4.0.0

/**
 * NoticeColumns generated by hbm2java
 */
public class NoticeColumns implements java.io.Serializable {

	private Integer id;
	private String columnName;
	private String description;

	public NoticeColumns() {
	}

	public NoticeColumns(String columnName, String description) {
		this.columnName = columnName;
		this.description = description;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getColumnName() {
		return this.columnName;
	}

	public void setColumnName(String columnName) {
		this.columnName = columnName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
