package cn.mutu.land.model;

// Generated 2016-9-24 16:08:24 by Hibernate Tools 4.0.0

/**
 * StaKfqConstruct generated by hbm2java
 */
public class StaKfqConstruct implements java.io.Serializable {

	private Integer id;
	private String dlmc;
	private String dldm;

	public StaKfqConstruct() {
	}

	public StaKfqConstruct(String dlmc, String dldm) {
		this.dlmc = dlmc;
		this.dldm = dldm;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getDlmc() {
		return this.dlmc;
	}

	public void setDlmc(String dlmc) {
		this.dlmc = dlmc;
	}

	public String getDldm() {
		return this.dldm;
	}

	public void setDldm(String dldm) {
		this.dldm = dldm;
	}

}
