package cn.mutu.land.model;

// Generated 2016-9-25 11:08:28 by Hibernate Tools 4.0.0

/**
 * StaKfq generated by hbm2java
 */
public class StaKfq implements java.io.Serializable {

	private Integer id;
	private String kfqmc;
	private String nf;
	private Double zzyd;
	private Double gyld;
	private Double qtbkjstd;
	private Double qtjtysyd;
	private Double qtggyd;
	private Double sfyd;
	private Double gkccyd;
	private Double yddgdtjqtyd;
	private Double wddgdtjqtyd;
	private Double hhyd;
	private Double jxyd;

	public StaKfq() {
	}

	public StaKfq(String kfqmc, String nf, Double zzyd, Double gyld,
			Double qtbkjstd, Double qtjtysyd, Double qtggyd, Double sfyd,
			Double gkccyd, Double yddgdtjqtyd, Double wddgdtjqtyd, Double hhyd,
			Double jxyd) {
		this.kfqmc = kfqmc;
		this.nf = nf;
		this.zzyd = zzyd;
		this.gyld = gyld;
		this.qtbkjstd = qtbkjstd;
		this.qtjtysyd = qtjtysyd;
		this.qtggyd = qtggyd;
		this.sfyd = sfyd;
		this.gkccyd = gkccyd;
		this.yddgdtjqtyd = yddgdtjqtyd;
		this.wddgdtjqtyd = wddgdtjqtyd;
		this.hhyd = hhyd;
		this.jxyd = jxyd;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getKfqmc() {
		return this.kfqmc;
	}

	public void setKfqmc(String kfqmc) {
		this.kfqmc = kfqmc;
	}

	public String getNf() {
		return this.nf;
	}

	public void setNf(String nf) {
		this.nf = nf;
	}

	public Double getZzyd() {
		return this.zzyd;
	}

	public void setZzyd(Double zzyd) {
		this.zzyd = zzyd;
	}

	public Double getGyld() {
		return this.gyld;
	}

	public void setGyld(Double gyld) {
		this.gyld = gyld;
	}

	public Double getQtbkjstd() {
		return this.qtbkjstd;
	}

	public void setQtbkjstd(Double qtbkjstd) {
		this.qtbkjstd = qtbkjstd;
	}

	public Double getQtjtysyd() {
		return this.qtjtysyd;
	}

	public void setQtjtysyd(Double qtjtysyd) {
		this.qtjtysyd = qtjtysyd;
	}

	public Double getQtggyd() {
		return this.qtggyd;
	}

	public void setQtggyd(Double qtggyd) {
		this.qtggyd = qtggyd;
	}

	public Double getSfyd() {
		return this.sfyd;
	}

	public void setSfyd(Double sfyd) {
		this.sfyd = sfyd;
	}

	public Double getGkccyd() {
		return this.gkccyd;
	}

	public void setGkccyd(Double gkccyd) {
		this.gkccyd = gkccyd;
	}

	public Double getYddgdtjqtyd() {
		return this.yddgdtjqtyd;
	}

	public void setYddgdtjqtyd(Double yddgdtjqtyd) {
		this.yddgdtjqtyd = yddgdtjqtyd;
	}

	public Double getWddgdtjqtyd() {
		return this.wddgdtjqtyd;
	}

	public void setWddgdtjqtyd(Double wddgdtjqtyd) {
		this.wddgdtjqtyd = wddgdtjqtyd;
	}

	public Double getHhyd() {
		return this.hhyd;
	}

	public void setHhyd(Double hhyd) {
		this.hhyd = hhyd;
	}

	public Double getJxyd() {
		return this.jxyd;
	}

	public void setJxyd(Double jxyd) {
		this.jxyd = jxyd;
	}

}
