package cn.mutu.land.model;

// Generated 2015-6-18 21:16:26 by Hibernate Tools 4.0.0

/**
 * SystemMap generated by hbm2java
 */
public class SystemMap implements java.io.Serializable {

	private Integer mapId;
	private Integer mapPid;
	private String mapGroup;
	private String mapName;
	private String mapKey;
	private String mapUrl;
	private String description;

	public SystemMap() {
	}

	public SystemMap(Integer mapPid, String mapGroup, String mapName,
			String mapKey, String mapUrl, String description) {
		this.mapPid = mapPid;
		this.mapGroup = mapGroup;
		this.mapName = mapName;
		this.mapKey = mapKey;
		this.mapUrl = mapUrl;
		this.description = description;
	}

	public Integer getMapId() {
		return this.mapId;
	}

	public void setMapId(Integer mapId) {
		this.mapId = mapId;
	}

	public Integer getMapPid() {
		return this.mapPid;
	}

	public void setMapPid(Integer mapPid) {
		this.mapPid = mapPid;
	}

	public String getMapGroup() {
		return this.mapGroup;
	}

	public void setMapGroup(String mapGroup) {
		this.mapGroup = mapGroup;
	}

	public String getMapName() {
		return this.mapName;
	}

	public void setMapName(String mapName) {
		this.mapName = mapName;
	}

	public String getMapKey() {
		return this.mapKey;
	}

	public void setMapKey(String mapKey) {
		this.mapKey = mapKey;
	}

	public String getMapUrl() {
		return this.mapUrl;
	}

	public void setMapUrl(String mapUrl) {
		this.mapUrl = mapUrl;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
