package cn.mutu.land.model;

// Generated 2015-5-27 18:43:10 by Hibernate Tools 4.0.0

/**
 * UUserRole generated by hbm2java
 */
public class UUserRole implements java.io.Serializable {

	private Integer id;
	private String username;
	private Integer roleid;

	public UUserRole() {
	}

	public UUserRole(String username, Integer roleid) {
		this.username = username;
		this.roleid = roleid;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public Integer getRoleid() {
		return this.roleid;
	}

	public void setRoleid(Integer roleid) {
		this.roleid = roleid;
	}

}
