/*
 * File: app/store/system_roleNameStore.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.system_roleNameStore', {
    extend: 'Ext.data.Store',
    alias: 'store.system_roleNameStore',

    requires: [
        'Ext.data.field.String'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'system_roleNameStore',
            data: [
                {
                    displayName: '查询',
                    roleName: 'ROLE_OPER'
                },
                {
                    displayName: '查询、添加、更新',
                    roleName: 'ROLE_USER'
                },
                {
                    displayName: '查询、添加、更新、删除',
                    roleName: 'ROLE_ADMIN'
                }
            ],
            fields: [
                {
                    type: 'string',
                    name: 'displayName'
                },
                {
                    type: 'string',
                    name: 'roleName'
                }
            ]
        }, cfg)]);
    }
});