/*
 * File: app/store/tmematic_LCCT_EndYearStore.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.tmematic_LCCT_EndYearStore', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.field.Field'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'tmematic_LCCT_EndYearStore',
            data: [
                {
                    name: '2016',
                    value: '2016'
                },
                {
                    name: '2015',
                    value: '2015'
                },
                {
                    name: '2014',
                    value: '2014'
                },
                {
                    name: '2013',
                    value: '2013'
                },
                {
                    name: '2012',
                    value: '2012'
                },
                {
                    name: '2011',
                    value: '2011'
                },
                {
                    name: '2010',
                    value: '2010'
                }
            ],
            fields: [
                {
                    name: 'name'
                },
                {
                    name: 'value'
                }
            ]
        }, cfg)]);
    }
});