/*
 * File: app/model/BusinessInfoModel.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.BusinessInfoModel', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Field'
    ],

    fields: [
        {
            name: 'id'
        },
        {
            name: 'businessId'
        },
        {
            name: 'businessName'
        },
        {
            name: 'businessAddress'
        },
        {
            name: 'businessZdcode'
        },
        {
            name: 'businessEvalueRange'
        },
        {
            name: 'businessIndustryType'
        },
        {
            name: 'businessIndustryCode'
        },
        {
            name: 'businessWorker'
        },
        {
            name: 'businessKfq'
        },
        {
            name: 'businessKfqCode'
        },
        {
            name: 'businessKfqType'
        },
        {
            name: 'businessDevArea'
        },
        {
            name: 'businessAdvance'
        },
        {
            name: 'businessPreInvestment'
        },
        {
            name: 'businessActInvestment'
        },
        {
            name: 'businessIncome'
        },
        {
            name: 'businessProduct'
        },
        {
            name: 'businessTax'
        },
        {
            name: 'businessArea'
        },
        {
            name: 'businessArea1'
        },
        {
            name: 'businessArea2'
        },
        {
            name: 'businessArea3'
        },
        {
            name: 'businessArea4'
        },
        {
            name: 'businessArea5'
        },
        {
            name: 'businessArea6'
        },
        {
            name: 'businessArea7'
        },
        {
            name: 'businessBuildingArea'
        },
        {
            name: 'businessPlotRatio'
        },
        {
            name: 'businessOutdoorArea'
        },
        {
            name: 'businessBuildingCoeficient'
        }
    ]
});