/*
 * File: app/view/business_info.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.business_info', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.business_info',

    requires: [
        'MyApp.view.business_infoViewModel'
    ],

    viewModel: {
        type: 'business_info'
    },
    height: 503,
    id: 'business_info',
    width: 666,
    layout: 'absolute',
    title: '企业信息录入'

});