/*
 * File: app/view/business_uploadPhoto.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.business_uploadPhoto', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.business_uploadPhoto',

    requires: [
        'MyApp.view.business_uploadPhotoViewModel',
        'Ext.form.Panel',
        'Ext.button.Button',
        'Ext.form.field.TextArea',
        'Ext.grid.Panel',
        'Ext.grid.column.RowNumberer',
        'Ext.grid.column.Date',
        'Ext.grid.View',
        'Ext.Img'
    ],

    viewModel: {
        type: 'business_uploadphoto'
    },
    height: 491,
    width: 959,
    layout: 'border',
    title: '企业上传图片数据',
    defaultListenerScope: true,

    items: [
        {
            xtype: 'panel',
            region: 'west',
            split: true,
            width: '50%',
            layout: 'border',
            title: '',
            items: [
                {
                    xtype: 'form',
                    region: 'north',
                    autoScroll: true,
                    height: '50%',
                    id: 'photo_info',
                    layout: 'absolute',
                    title: '图片信息录入',
                    jsonSubmit: true,
                    url: 'add_Photos',
                    items: [
                        {
                            xtype: 'button',
                            handler: function() {
                                var myform = Ext.getCmp('photo_info').getForm();
                                var choose=Ext.getCmp('photoPath').value;
                                //var photo_path=Ext.getCmp('photo_path');
                                //var path=Ext.widget('photoPath').value;
                                if (myform.isValid())
                                {
                                    console.log("控件有效");

                                    console.log(choose);
                                    myform.submit({
                                        //url : 'add_picture',
                                        success : function (form, action)
                                        {
                                            console.log("成功进入");
                                            Ext.Msg.alert('成功', '图片上传成功。');
                                            var mystore = Ext.StoreMgr.get('Business_photoStore'); //获得store对象
                                            mystore.reload();
                                            var xtype = 'business_uploadPhoto';
                                            var mainView = Ext.getCmp('mainView');
                                            mainView.removeAll();
                                            mainView.add(Ext.widget(xtype));
                                        },
                                        failure: function(form, action){
                                            Ext.Msg.alert('失败', '图片上传失败，请重试。');
                                        }
                                    });
                                }
                                else
                                {
                                    Ext.Msg.alert('注意', '填写的信息有误，请检查！');
                                }
                            },
                            x: 270,
                            y: 340,
                            text: '提交审核'
                        },
                        {
                            xtype: 'textareafield',
                            x: 30,
                            y: 250,
                            width: 360,
                            fieldLabel: '备注',
                            labelWidth: 70,
                            name: 'other',
                            value: '无'
                        },
                        {
                            xtype: 'textfield',
                            x: 30,
                            y: 140,
                            id: 'title_photo',
                            fieldLabel: '图片标题',
                            labelWidth: 70,
                            name: 'photoTitle'
                        },
                        {
                            xtype: 'textfield',
                            x: 30,
                            y: 190,
                            fieldLabel: '上传用户',
                            labelWidth: 70,
                            name: 'uploadUser',
                            value: '企业用户'
                        },
                        {
                            xtype: 'textfield',
                            x: 30,
                            y: 40,
                            fieldLabel: '项目编号',
                            labelWidth: 70,
                            name: 'proCode',
                            value: '20160710****'
                        },
                        {
                            xtype: 'textfield',
                            x: 30,
                            y: 90,
                            id: 'photoPath',
                            width: 390,
                            fieldLabel: '上传图片',
                            labelWidth: 70,
                            name: 'photoPath',
                            inputType: 'file',
                            listeners: {
                                change: 'onFilesChange'
                            }
                        }
                    ]
                },
                {
                    xtype: 'gridpanel',
                    region: 'center',
                    autoScroll: true,
                    title: '图片列表',
                    store: 'Business_photoStore',
                    columns: [
                        {
                            xtype: 'rownumberer',
                            width: 60,
                            dataIndex: 'string',
                            text: '序号'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 200,
                            defaultWidth: 200,
                            dataIndex: 'photoTitle',
                            text: '图片标题'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'uploadUser',
                            text: '上传用户'
                        },
                        {
                            xtype: 'datecolumn',
                            width: 159,
                            dataIndex: 'upDate',
                            text: '上传时间'
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'panel',
            region: 'center',
            layout: 'border',
            animCollapse: false,
            collapseDirection: 'left',
            collapseFirst: false,
            collapsed: false,
            collapsible: false,
            title: '图片预览',
            titleAlign: 'center',
            titleCollapse: false,
            items: [
                {
                    xtype: 'image',
                    region: 'center',
                    id: 'photo_preview',
                    src: 'images/login/login_center_left.jpg'
                }
            ]
        }
    ],

    onFilesChange: function(field, newValue, oldValue, eOpts) {
        var title_photo = Ext.getCmp("title_photo");
        var photoPreview=Ext.getCmp("photo_preview");
        //var photoFiles=document.getElementById("photo_files")
        var url="images/login/"+newValue.substring(newValue.lastIndexOf("\\")+1);
        var name = newValue.substring(newValue.lastIndexOf("\\")+1, newValue.lastIndexOf("."));
        console.log(name);
        title_photo.setValue(name);

        //url = window.URL.createObjectURL(this.field);
        console.log(url);
        photoPreview.setSrc(url);
        /*//加入地图的js文件
        var head = document.getElementsByTagName('head')[0];
        var script= document.createElement("script");"images/login/meat.jpg"
        script.type = "text/javascript";
        script.src="mapjs/uploadPhoto.js";
        head.appendChild(script);*/
    }

});