/*
 * File: app/view/dxqy_photoPreview.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.dxqy_photoPreview', {
    extend: 'Ext.window.Window',
    alias: 'widget.dxqy_photoPreview',

    requires: [
        'MyApp.view.dxqy_photouploadViewModel1',
        'Ext.form.Panel',
        'Ext.form.FieldSet',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Date',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'dxqy_photopreview'
    },
    height: 450,
    id: 'dxqy_photoPreview',
    width: 750,
    layout: 'border',
    title: '企业照片预览',
    defaultListenerScope: true,

    items: [
        {
            xtype: 'panel',
            region: 'center',
            split: true,
            layout: 'border',
            title: '',
            items: [
                {
                    xtype: 'form',
                    region: 'west',
                    split: true,
                    id: 'bus_photoinformation2',
                    width: 380,
                    layout: 'border',
                    items: [
                        {
                            xtype: 'form',
                            region: 'center',
                            split: false,
                            id: 'photoInfoForm1',
                            manageHeight: false,
                            items: [
                                {
                                    xtype: 'fieldset',
                                    height: 400,
                                    margin: 5,
                                    width: 350,
                                    title: '基本信息',
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            id: 'photosNameIdForm1',
                                            width: 320,
                                            fieldLabel: '图片名称',
                                            name: 'photosName',
                                            submitValue: false,
                                            editable: false
                                        },
                                        {
                                            xtype: 'textfield',
                                            width: 320,
                                            fieldLabel: '企业名称',
                                            name: 'qymc',
                                            editable: false
                                        },
                                        {
                                            xtype: 'textfield',
                                            width: 320,
                                            fieldLabel: '企业地址',
                                            name: 'qydz',
                                            editable: false
                                        },
                                        {
                                            xtype: 'textfield',
                                            width: 320,
                                            fieldLabel: '企业人数',
                                            name: 'qyrs',
                                            editable: false
                                        },
                                        {
                                            xtype: 'textfield',
                                            width: 320,
                                            fieldLabel: '宗地编号',
                                            name: 'zdbh',
                                            editable: false
                                        },
                                        {
                                            xtype: 'combobox',
                                            width: 320,
                                            fieldLabel: '上报年份',
                                            name: 'sbnf',
                                            submitValue: false,
                                            editable: false
                                        },
                                        {
                                            xtype: 'textfield',
                                            width: 320,
                                            fieldLabel: '所属开发区',
                                            name: 'kfqmc',
                                            submitValue: false,
                                            editable: false
                                        },
                                        {
                                            xtype: 'textfield',
                                            width: 320,
                                            fieldLabel: '开发区代码',
                                            name: 'kfqdm',
                                            editable: false
                                        },
                                        {
                                            xtype: 'textfield',
                                            width: 320,
                                            fieldLabel: '开发区类型',
                                            name: 'kfqlx',
                                            editable: false
                                        },
                                        {
                                            xtype: 'textfield',
                                            width: 320,
                                            fieldLabel: '行业类别',
                                            name: 'hylb',
                                            editable: false
                                        },
                                        {
                                            xtype: 'combobox',
                                            width: 320,
                                            fieldLabel: '行业代码',
                                            name: 'hydm',
                                            submitValue: false,
                                            editable: false,
                                            store: 'dxqy_uploadStore'
                                        },
                                        {
                                            xtype: 'datefield',
                                            id: 'tbrq1',
                                            width: 320,
                                            fieldLabel: '填报日期',
                                            name: 'tbrq',
                                            submitValue: false,
                                            editable: false
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            hidden: true,
                                            fieldLabel: 'id',
                                            name: 'id'
                                        }
                                    ]
                                }
                            ],
                            listeners: {
                                afterrender: 'onPhotoInfo1AfterRender'
                            }
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    margins: '',
                    region: 'center',
                    autoScroll: true,
                    id: 'photoPreviewPanel1',
                    margin: 10,
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'button',
                                    handler: function(button, e) {
                                        var width= $('#blah1').attr('width');
                                        width=width.replace("%","");
                                        if(width>=100)return;
                                        else if(width>=80)
                                        $('#blah1').attr('width', '100%');
                                        else if(width>=60)
                                        $('#blah1').attr('width', '80%');
                                        else if(width>=40)
                                        $('#blah1').attr('width', '60%');
                                        else if(width>=20)
                                        $('#blah1').attr('width', '40%');
                                        else $('#blah1').attr('width', '20%');
                                        console.log($('#blah1').attr('width'));
                                    },
                                    text: '放大'
                                },
                                {
                                    xtype: 'button',
                                    handler: function(button, e) {
                                        var width= $('#blah1').attr('width');
                                        width=width.replace("%","");
                                        if(width<=10)return;
                                        else if(width<=20)
                                        $('#blah1').attr('width', '10%');
                                        else if(width<=40)
                                        $('#blah1').attr('width', '20%');
                                        else if(width<=60)
                                        $('#blah1').attr('width', '40%');
                                        else if(width<=80)
                                        $('#blah1').attr('width', '60%');
                                        else $('#blah1').attr('width', '80%');
                                        console.log($('#blah1').attr('width'));
                                    },
                                    text: '缩小'
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ],

    onPhotoInfo1AfterRender: function(component, eOpts) {
        //获取当前填报时间
        var registerdateField = Ext.getCmp('tbrq1');
        var dateStr = "";
        var myDate = new Date();
        dateStr += myDate.getFullYear();    //获取完整的年份(4位,1970-????)
        dateStr += "-" + (myDate.getMonth()+1);       //获取当前月份(0-11,0代表1月)
        dateStr += "-" +myDate.getDate();        //获取当前日(1-31)
        registerdateField.setValue(dateStr);
    }

});