/*
 * File: app/view/dxqy_mapPreview.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.dxqy_mapPreview', {
    extend: 'Ext.window.Window',
    alias: 'widget.dxqy_mapPreview',

    requires: [
        'MyApp.view.dxqy_mapuploadViewModel1'
    ],

    viewModel: {
        type: 'dxqy_mappreview'
    },
    height: 625,
    hidden: false,
    html: '<iframe src=\'public/mapUpload/dxqy_mapupload.html?qymc=海林经济技术开发区\' scrolling=\'yes\' frameborder=0 width=100% height=100%></iframe>',
    id: 'dxqy_mapPreview',
    width: 777,
    layout: 'border',
    title: '上传企业位置'

});