/*
 * File: app/view/law_TypesManagerWindow.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.law_TypesManagerWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.law_TypesManagerWindow',

    requires: [
        'Ext.grid.Panel',
        'Ext.grid.column.RowNumberer',
        'Ext.grid.View',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.selection.CheckboxModel'
    ],

    height: 351,
    id: 'law_TypesManagerWindow',
    width: 537,
    layout: 'fit',
    title: '法律法规类型管理',
    defaultListenerScope: true,

    items: [
        {
            xtype: 'gridpanel',
            id: 'law_TypesManagerGrid',
            store: 'law_TypesStore',
            columns: [
                {
                    xtype: 'rownumberer'
                },
                {
                    xtype: 'gridcolumn',
                    width: 200,
                    dataIndex: 'lawType',
                    text: '栏目名称'
                },
                {
                    xtype: 'gridcolumn',
                    width: 250,
                    dataIndex: 'description',
                    text: '描述'
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'button',
                            icon: 'images/table/add.png',
                            text: '添加栏目',
                            listeners: {
                                click: 'onButtonClick'
                            }
                        },
                        {
                            xtype: 'button',
                            icon: 'images/table/edit.png',
                            text: '修改栏目',
                            listeners: {
                                click: 'onButtonClick1'
                            }
                        },
                        {
                            xtype: 'button',
                            icon: 'images/table/delete.png',
                            text: '删除栏目',
                            listeners: {
                                click: 'onButtonClick2'
                            }
                        }
                    ]
                }
            ],
            selModel: {
                selType: 'checkboxmodel'
            }
        }
    ],

    onButtonClick: function(button, e, eOpts) {
        var win = Ext.widget('law_TypeWindow');
        win.show();
    },

    onButtonClick1: function(button, e, eOpts) {
        //获取数据
        var records = Ext.getCmp('law_TypesManagerGrid').getSelection();
        if (records.length === 0){
            Ext.Msg.alert('提示', '请选择一条数据后再修改信息。');
            return;
        } else if(records.length >1){
            Ext.Msg.alert('提示', '每次只能修改一条信息，请重新选择。');
            return;
        }
        //启动窗口
        var win = Ext.widget('law_TypeWindow');
        win.setTitle('修改栏目');
        win.show();

        //改变Ajax url
        var form = Ext.getCmp('law_TypeForm').getForm();
        form.loadRecord(records[0]);
        form.url='update_LawType';
    },

    onButtonClick2: function(button, e, eOpts) {
        //获取数据
        var records = Ext.getCmp('law_TypesManagerGrid').getSelection();
        if (records.length === 0){
           Ext.Msg.alert('提示', '请选择一条数据后再点击删除按钮。');
           return;
        }else if(records.length >1){
           Ext.Msg.alert('提示', '每次只能删除一条栏目。');
           return;
        }
        var id = records[0].get("id");
        var columnName= records[0].get("lawType");
        Ext.Msg.confirm('提示', '您正在删除<br/>[' +columnName+']栏目。<br/> 确认删除？', getResult);


        function getResult(confirm)
        {
            console.log('confirm:', confirm);
            if (confirm == "yes"){
                Ext.Ajax.request(
                {
                    url : 'del_LawTypeById',
                    params :
                    {
                        id : id
                    },
                    success : function (response){
                        Ext.Msg.alert('成功提示', '记录删除成功。');
                        var mystore = Ext.StoreMgr.get('law_TypesStore');
                        mystore.load();
                    },
                    failure : function (response){
                        Ext.Msg.alert('失败提示', '记录删除失败。');
                    }
                });
            }
        }
    }

});