/*
 * File: app/view/MyPanel24.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyPanel24', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.mypanel24',

    requires: [
        'MyApp.view.MyPanel24ViewModel'
    ],

    viewModel: {
        type: 'mypanel24'
    },
    height: 445,
    id: 'zd_information1',
    width: 1010,
    layout: 'absolute',
    title: '宗地信息填报'

});