/*
 * File: app/view/mywindow.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.mywindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.mywindow',

    requires: [
        'MyApp.view.MyWindowViewModel',
        'Ext.form.Panel',
        'Ext.form.field.Text',
        'Ext.toolbar.Toolbar',
        'Ext.toolbar.Fill',
        'Ext.button.Button',
        'Ext.toolbar.Spacer'
    ],

    viewModel: {
        type: 'mywindow'
    },
    height: 211,
    id: 'mywindow',
    width: 400,
    layout: 'border',
    title: '新增宗地信息',

    items: [
        {
            xtype: 'form',
            region: 'center',
            id: 'push_businessinfo',
            bodyPadding: 10,
            title: '',
            jsonSubmit: true,
            url: 'add_BusinessInfo',
            items: [
                {
                    xtype: 'textfield',
                    fieldLabel: '企业代码',
                    name: 'businessId'
                },
                {
                    xtype: 'textfield',
                    fieldLabel: '企业名称',
                    name: 'businessName'
                },
                {
                    xtype: 'textfield',
                    fieldLabel: '企业地址',
                    name: 'businessAddress'
                },
                {
                    xtype: 'textfield',
                    fieldLabel: '企业人数',
                    name: 'businessWorker'
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    items: [
                        {
                            xtype: 'tbfill',
                            width: ''
                        },
                        {
                            xtype: 'button',
                            text: '取消'
                        },
                        {
                            xtype: 'tbspacer',
                            width: 40
                        },
                        {
                            xtype: 'button',
                            handler: function() {
                                var myform = Ext.getCmp('push_businessinfo').getForm();
                                if (myform.isValid())
                                {
                                    myform.submit({
                                        //url : 'add_NoticeNews',
                                        success : function (form, action)
                                        {
                                            Ext.Msg.alert('成功', '提交成功。');
                                            var mystore = Ext.StoreMgr.get('BusinessInfo'); //获得store对象
                                            mystore.reload();

                                            var win =Ext.getCmp('mywindow');
                                            win.close();
                                        },
                                        failure: function(form, action){
                                            Ext.Msg.alert('失败', '内容发布失败，请重试。');
                                        }
                                    });
                                }
                                else
                                {
                                    Ext.Msg.alert('注意', '填写的信息有误，请检查！');
                                }
                            },
                            text: '添加'
                        },
                        {
                            xtype: 'tbspacer',
                            width: 20
                        }
                    ]
                }
            ]
        }
    ]

});