/*
 * File: app/view/notice_Manage.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.notice_Manage', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.notice_Manage',

    requires: [
        'MyApp.view.thematic_LanduseConstructionContrastViewModel22'
    ],

    viewModel: {
        type: 'notice_manage'
    },
    height: 588,
    width: 786,
    title: '内容管理'

});