/*
 * File: app/view/notice_Columns.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.notice_Columns', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.notice_Columns',

    requires: [
        'Ext.grid.Panel',
        'Ext.grid.column.RowNumberer',
        'Ext.grid.View',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.selection.CheckboxModel'
    ],

    height: 588,
    width: 786,
    layout: 'fit',
    title: '通知通告栏目管理',
    defaultListenerScope: true,

    items: [
        {
            xtype: 'gridpanel',
            id: 'notice_ColumnsGrid',
            store: 'notice_columnsStore',
            columns: [
                {
                    xtype: 'rownumberer'
                },
                {
                    xtype: 'gridcolumn',
                    width: 200,
                    dataIndex: 'group',
                    text: '栏目组'
                },
                {
                    xtype: 'gridcolumn',
                    width: 200,
                    dataIndex: 'column',
                    text: '栏目名称'
                },
                {
                    xtype: 'gridcolumn',
                    width: 200,
                    dataIndex: 'description',
                    text: '备注'
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'button',
                            icon: 'images/table/add.png',
                            text: '添加栏目',
                            listeners: {
                                click: 'onButtonClick'
                            }
                        },
                        {
                            xtype: 'button',
                            icon: 'images/table/edit.png',
                            text: '修改栏目',
                            listeners: {
                                click: 'onButtonClick1'
                            }
                        },
                        {
                            xtype: 'button',
                            icon: 'images/table/delete.png',
                            text: '删除栏目',
                            listeners: {
                                click: 'onButtonClick2'
                            }
                        }
                    ]
                }
            ],
            selModel: {
                selType: 'checkboxmodel'
            }
        }
    ],

    onButtonClick: function(button, e, eOpts) {
        var win = Ext.widget('notice_ColumnsWindow');
        win.show();
        var form = Ext.getCmp('notice_ColumnsWindowForm');
        form.url = 'add_NoticeColumns';
    },

    onButtonClick1: function(button, e, eOpts) {

    },

    onButtonClick2: function(button, e, eOpts) {

    }

});