/*
 * File: app/view/notice_Manage.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.notice_Manage', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.notice_Manage',

    requires: [
        'Ext.grid.Panel',
        'Ext.grid.column.RowNumberer',
        'Ext.grid.column.Date',
        'Ext.grid.column.Action',
        'Ext.grid.View',
        'Ext.toolbar.Toolbar',
        'Ext.form.field.Text',
        'Ext.button.Button',
        'Ext.toolbar.Separator',
        'Ext.selection.CheckboxModel'
    ],

    height: 588,
    width: 786,
    layout: 'fit',
    title: '内容管理',

    items: [
        {
            xtype: 'gridpanel',
            id: 'notice_NewsManageGrid',
            store: 'notice_newStore',
            columns: [
                {
                    xtype: 'rownumberer'
                },
                {
                    xtype: 'gridcolumn',
                    width: 120,
                    dataIndex: 'column',
                    text: '所属栏目'
                },
                {
                    xtype: 'gridcolumn',
                    width: 250,
                    dataIndex: 'title',
                    text: '标题'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'author',
                    text: '作者'
                },
                {
                    xtype: 'datecolumn',
                    width: 120,
                    dataIndex: 'datetime',
                    text: '发表时间'
                },
                {
                    xtype: 'actioncolumn',
                    dataIndex: 'attachment',
                    text: '附件'
                },
                {
                    xtype: 'gridcolumn',
                    width: 200,
                    dataIndex: 'description',
                    text: '备注'
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'textfield',
                            id: 'system_MapManage_SearchText1'
                        },
                        {
                            xtype: 'button',
                            icon: 'images/table/search.png',
                            text: '查询'
                        },
                        {
                            xtype: 'button',
                            icon: 'images/table/preview.png',
                            text: '预览'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            icon: 'images/table/add.png',
                            text: '添加'
                        },
                        {
                            xtype: 'button',
                            icon: 'images/table/edit.png',
                            text: '修改'
                        },
                        {
                            xtype: 'button',
                            icon: 'images/table/delete.png',
                            text: '删除'
                        }
                    ]
                }
            ],
            selModel: {
                selType: 'checkboxmodel'
            }
        }
    ]

});