/*
 * File: app/view/survey_IndexCurrentValueCalculation.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.survey_IndexCurrentValueCalculation', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.survey_IndexCurrentValueCalculation',

    requires: [
        'MyApp.view.thematic_LanduseConstructionContrastViewModel14'
    ],

    viewModel: {
        type: 'survey_indexcurrentvaluecalculation'
    },
    height: 588,
    width: 786,
    title: '指标现状值计算'

});