/*
 * File: app/view/sys_MapAttrNameIndexWindow.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.sys_MapAttrNameIndexWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.sys_MapAttrNameIndexWindow',

    requires: [
        'Ext.grid.Panel',
        'Ext.grid.column.RowNumberer',
        'Ext.grid.View',
        'Ext.toolbar.Toolbar',
        'Ext.form.field.Text',
        'Ext.button.Button',
        'Ext.selection.CheckboxModel'
    ],

    height: 398,
    id: 'sys_MapAttrNameIndexWindow',
    width: 654,
    layout: 'fit',
    title: '地图字段中英文对照',
    defaultListenerScope: true,

    items: [
        {
            xtype: 'gridpanel',
            id: 'sys_MapAttrNameIndexGrid',
            store: 'sys_MapAttrNameIndexStore',
            columns: [
                {
                    xtype: 'rownumberer',
                    width: 30
                },
                {
                    xtype: 'gridcolumn',
                    width: 100,
                    dataIndex: 'enName',
                    text: '英文名'
                },
                {
                    xtype: 'gridcolumn',
                    width: 150,
                    dataIndex: 'cnName',
                    text: '中文名称'
                },
                {
                    xtype: 'gridcolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                        if(value){
                            return '是';
                        }else{
                            return '否';
                        }
                    },
                    width: 50,
                    dataIndex: 'enable',
                    text: '启用'
                },
                {
                    xtype: 'gridcolumn',
                    width: 80,
                    dataIndex: 'unit',
                    text: '单位'
                },
                {
                    xtype: 'gridcolumn',
                    width: 100,
                    dataIndex: 'byTableName',
                    text: '来自表格'
                },
                {
                    xtype: 'gridcolumn',
                    width: 100,
                    dataIndex: 'comment',
                    text: '备注'
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'textfield',
                            id: 'sys_MapAttrNameIndexSearchkeyField'
                        },
                        {
                            xtype: 'button',
                            icon: 'images/table/search.png',
                            text: '搜索',
                            listeners: {
                                click: 'onButtonClick'
                            }
                        },
                        {
                            xtype: 'button',
                            icon: 'images/table/add.png',
                            text: '添加字段对照',
                            listeners: {
                                click: 'onButtonClick3'
                            }
                        },
                        {
                            xtype: 'button',
                            icon: 'images/table/edit.png',
                            text: '修改字段对照',
                            listeners: {
                                click: 'onButtonClick1'
                            }
                        },
                        {
                            xtype: 'button',
                            icon: 'images/table/delete.png',
                            text: '删除',
                            listeners: {
                                click: 'onButtonClick2'
                            }
                        }
                    ]
                }
            ],
            selModel: {
                selType: 'checkboxmodel'
            }
        }
    ],

    onButtonClick: function(button, e, eOpts) {
        var searchKeyword = Ext.getCmp('sys_MapAttrNameIndexSearchkeyField').getValue();
        var mystore = Ext.StoreMgr.get('sys_MapAttrNameIndexStore'); //获得store对象
        //在load事件中添加参数
        mystore.load({
            params :{searchKeyword : searchKeyword}
        });
    },

    onButtonClick3: function(button, e, eOpts) {
        var win = Ext.widget('sys_MapAddAttrNameIndexWindow');
        win.show();
    },

    onButtonClick1: function(button, e, eOpts) {
        //获取数据
        var records = Ext.getCmp('sys_MapAttrNameIndexGrid').getSelection();
        if (records.length === 0){
            Ext.Msg.alert('提示', '请选择一条数据后再修改信息。');
            return;
        } else if(records.length >1){
            Ext.Msg.alert('提示', '每次只能修改一条信息，请重新选择。');
            return;
        }
        //启动窗口
        var win = Ext.widget('sys_MapAddAttrNameIndexWindow');
        win.setTitle('修改字段中英文对照');
        win.show();

        //改变Ajax url
        var form = Ext.getCmp('sys_MapAttrNameIndexForm').getForm();
        form.loadRecord(records[0]);
        form.url='update_MapAttrNameIndex';
    },

    onButtonClick2: function(button, e, eOpts) {
        //获取数据
        var records = Ext.getCmp('sys_MapAttrNameIndexGrid').getSelection();
        var count = records.length;
        if (count === 0){
           Ext.Msg.alert('提示', '请选择一条数据后再点击删除按钮。');
           return;
        }
        console.log("records:",records);
        var ids =new Array(count);
        for(var i = 0;i<count;i++){
            ids[i] = records[i].get('id');
        }
        console.log("ids:",ids);
        Ext.Msg.confirm('提示', '您正在删除<br/>[' +count+']条数据。<br/> 确认删除？', getResult);


        function getResult(confirm)
        {
            console.log('confirm:', confirm);
            if (confirm == "yes"){
                Ext.Ajax.request(
                {
                    url : 'del_MapAttrNameIndex',
                    params :
                    {
                        ids : ids
                    },
                    success : function (response){
                        Ext.Msg.alert('成功提示', '记录删除成功。');
                        var mystore = Ext.StoreMgr.get('sys_MapAttrNameIndexStore');
                        mystore.load();
                    },
                    failure : function (response){
                        Ext.Msg.alert('失败提示', '记录删除失败。');
                    }
                });
            }
        }
    }

});