/*
 * File: app/view/system_MapManageTree.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.system_MapManageTree', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.system_MapManageTree',

    requires: [
        'Ext.tree.Panel',
        'Ext.tree.View',
        'Ext.tree.Column',
        'Ext.toolbar.Toolbar',
        'Ext.form.field.Text',
        'Ext.button.Button',
        'Ext.toolbar.Separator'
    ],

    height: 588,
    width: 931,
    layout: 'fit',
    title: '地图管理',
    defaultListenerScope: true,

    items: [
        {
            xtype: 'treepanel',
            autoScroll: true,
            height: 250,
            id: 'system_MapManageTreeGrid',
            width: 400,
            collapsible: true,
            store: 'systemManageMapTreeStore',
            folderSort: true,
            rootVisible: false,
            useArrows: true,
            viewConfig: {
                rootVisible: false
            },
            columns: [
                {
                    xtype: 'treecolumn',
                    width: 200,
                    dataIndex: 'kfqName',
                    text: 'Nodes'
                },
                {
                    xtype: 'gridcolumn',
                    width: 300,
                    dataIndex: 'mapName',
                    text: 'name'
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    id: '',
                    items: [
                        {
                            xtype: 'textfield',
                            id: 'system_MapManage_SearchText'
                        },
                        {
                            xtype: 'button',
                            icon: 'images/table/search.png',
                            text: '查询'
                        },
                        {
                            xtype: 'button',
                            icon: 'images/table/preview.png',
                            text: '预览'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            icon: 'images/table/add.png',
                            text: '添加'
                        },
                        {
                            xtype: 'button',
                            icon: 'images/table/edit.png',
                            text: '修改'
                        },
                        {
                            xtype: 'button',
                            icon: 'images/table/delete.png',
                            text: '删除'
                        }
                    ]
                }
            ],
            listeners: {
                beforerender: 'onSystem_MapManageTreeGridBeforeRender'
            }
        }
    ],

    onSystem_MapManageTreeGridBeforeRender: function(component, eOpts) {
        var store = Ext.create('Ext.data.TreeStore', {
                root: {
                    expanded: true,
                    children: [{
                        text: "detention",
                        leaf: true
                    }, {
                        text: "homework",
                        expanded: false,
                        children: [{
                            text: "book report",
                            leaf: true
                        }, {
                            text: "alegrbra",
                            leaf: true
                        }]
                    }, {
                        text: "buy lottery tickets",
                        leaf: true
                    }]
                }
            });

        //var store = Ext.StoreMgr.get('sys_TreeStore');
        //console.log("Store:",store);
        //component.setStore(store);

    }

});