/*
 * File: app/view/task_Locate.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.task_Locate', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.task_Locate',

    requires: [
        'Ext.grid.Panel',
        'Ext.grid.column.Column',
        'Ext.grid.View'
    ],

    height: 588,
    width: 786,
    layout: 'border',
    title: '任务定位',

    items: [
        {
            xtype: 'gridpanel',
            region: 'west',
            split: true,
            width: 285,
            title: '任务信息',
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'string',
                    text: '任务编号'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'string',
                    text: '任务名称'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'string',
                    text: '执行时间'
                }
            ]
        },
        {
            xtype: 'panel',
            region: 'center',
            split: true,
            title: '任务地图'
        }
    ]

});