/*
 * File: app/view/thematic_LanduseConstructionChangeTrend.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.thematic_LanduseConstructionChangeTrend', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.thematic_LanduseConstructionChangeTrend',

    requires: [
        'Ext.grid.Panel',
        'Ext.grid.View',
        'Ext.grid.column.RowNumberer',
        'Ext.toolbar.Toolbar',
        'Ext.form.field.ComboBox',
        'Ext.button.Button'
    ],

    autoScroll: true,
    height: 741,
    width: 786,
    layout: 'border',
    title: '土地利用结构变化趋势分析',
    defaultListenerScope: true,

    items: [
        {
            xtype: 'panel',
            region: 'center',
            split: true,
            html: '<div id = "thematic_LanduseConstructionChangeTrend_echart" class="echartsDiv"></div>',
            layout: 'fit',
            listeners: {
                afterrender: 'onPanelAfterRender1'
            }
        },
        {
            xtype: 'panel',
            region: 'south',
            split: true,
            height: 250,
            layout: 'fit',
            title: '',
            items: [
                {
                    xtype: 'gridpanel',
                    id: 'thematic_LCCT_Grid',
                    title: '历年土地利用结构统计数据',
                    columns: [
                        {
                            xtype: 'rownumberer'
                        }
                    ]
                }
            ]
        }
    ],
    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            items: [
                {
                    xtype: 'combobox',
                    id: 'thematicLCCT_KFQCombo',
                    renderData: 'return [\n    {"name": "2016","value": "2016"},\n    {"name": "2015","value": "2015"},\n    {"name": "2014","value": "2014"},\n    {"name": "2013","value": "2013"},\n    {"name": "2012","value": "2012"},\n    {"name": "2011","value": "2011"},\n    {"name": "2010","value": "2010"}\n];',
                    width: 250,
                    fieldLabel: '开发区',
                    labelWidth: 60,
                    autoLoadOnValue: true,
                    displayField: 'name',
                    store: 'thematic_LCCT_KFQStore',
                    valueField: 'value'
                },
                {
                    xtype: 'combobox',
                    id: 'thematicLCCT_StartYearCombo',
                    renderData: 'return [\n    {"name": "2016","value": "2016"},\n    {"name": "2015","value": "2015"},\n    {"name": "2014","value": "2014"},\n    {"name": "2013","value": "2013"},\n    {"name": "2012","value": "2012"},\n    {"name": "2011","value": "2011"},\n    {"name": "2010","value": "2010"}\n];',
                    width: 150,
                    fieldLabel: '起始年份',
                    labelWidth: 60,
                    value: '2012',
                    autoLoadOnValue: true,
                    displayField: 'name',
                    store: 'tmematic_LCCT_StartYearStore',
                    valueField: 'value',
                    valueNotFoundText: '时间超出范围'
                },
                {
                    xtype: 'combobox',
                    id: 'thematicLCCT_EndYearCombo',
                    renderData: 'return [\n    {"name": "2016","value": "2016"},\n    {"name": "2015","value": "2015"},\n    {"name": "2014","value": "2014"},\n    {"name": "2013","value": "2013"},\n    {"name": "2012","value": "2012"},\n    {"name": "2011","value": "2011"},\n    {"name": "2010","value": "2010"}\n];',
                    width: 150,
                    fieldLabel: '截止年份',
                    labelWidth: 60,
                    value: '2013',
                    autoLoadOnValue: true,
                    displayField: 'name',
                    store: 'tmematic_LCCT_EndYearStore',
                    valueField: 'value'
                },
                {
                    xtype: 'button',
                    id: 'thematicLCCT_SubmitButton',
                    text: '开始分析'
                },
                {
                    xtype: 'button',
                    handler: function(button, e) {
                        //加入地图的js文件
                        var head = document.getElementsByTagName('head')[0];
                        var script= document.createElement("script");
                        script.type = "text/javascript";
                        script.src="mapjs/dataImport.js";//thematic_LanduseConstructionChangeTrend_map.js
                        head.appendChild(script);
                        Ext.Msg.alert("同步完成");
                    },
                    text: '测试导入数据库'
                }
            ]
        }
    ],
    listeners: {
        afterrender: 'onPanelAfterRender'
    },

    onPanelAfterRender1: function(component, eOpts) {
        var head = document.getElementsByTagName('head')[0];
        var script= document.createElement("script");
        script.type = "text/javascript";
        script.src="echarts/thematic_LanduseConstructionChangeTrend.js";//"mapjs/dataImport.js";//
        head.appendChild(script);
    },

    onPanelAfterRender: function(component, eOpts) {
        //加入地图的js文件
        var head = document.getElementsByTagName('head')[0];
        var script= document.createElement("script");
        script.type = "text/javascript";
        script.src="mapjs/thematic_LanduseConstructionChangeTrend_map.js";//thematic_LanduseConstructionChangeTrend_map.js
        head.appendChild(script);
    }

});